### ISSUE TITLE
Create shared banking infrastructure

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#1]
Done:

- [x] Bank account created
- [x] Everyone has access to it
- [x] Payment into account
- [ ] Change existing substription to use account (Google, Digital ocean, mailchimp etc)

**Comment by theblockstalk** [comment]
Hey @kamitor I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/tonomy-management-62c44570ca798a001824dd4d/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by kamitor** [comment]
Meeting this friday

**Comment by kamitor** [comment]
Waiting on the bank

**Comment by kamitor** [comment]
Calling bank again

**Comment by kamitor** [comment]
KVK 86537288

**Comment by kamitor** [comment]
let them know we are a bit frustrated that it is taking so long. We're upto 6 weeks now.
They were adiment that they would send a "question list" next week that we have to fill in. 

(why the fuck is it taking so long to send a question list is beyond me)

**Comment by kamitor** [comment]
update bank got new email

**Comment by Mrak1985** [comment]
@kamitor evidence

**Comment by theblockstalk** [comment]
this for next task
-  Change existing substription to use account (Google, Digital ocean, mailchimp etc)
