### ISSUE TITLE
Finalize and submit Pomelo proposal

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#101]
**Definition of done:**

- [x] Take feedback from review
- [x] Finalize proposal
- [x] Submit proposal by July 27

**Comment by theblockstalk** [comment]
we still need to add a video of the mockup showing the two flows:
- choose recovery buddies,
- recover using recovery buddies

**Comment by Mrak1985** [comment]
@Carrie22022 can you update this task please
