### ISSUE TITLE
Marketing for pomelo grant when it goes public 27 July

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#105]
Need to pump out the grant on marketing channels. Make sure that wetag other relevant entities like ENF, greymass and others

Especially on telegram channels

Jack had a few private ones like
https://t.me/identity_on_eosio
Also slack identity

- [x] necessary posts are prepared for LinkedIn, twitter, EOSIO channels like Telegram
- [x] Reviewed by one person
- [ ] posts are submitted on appropriate channels

**Comment by theblockstalk** [comment]
Pomelo grant is public NOW! this is high priority. Pomelo grant CLOSES on July 27 @Mrak1985

**Comment by theblockstalk** [comment]
Places shared

- [x] https://twitter.com/theblockstalk/status/1556652667715436544
- [x] https://www.linkedin.com/posts/jack-tanner_pomelo-activity-6962712790318882818-OXph/?utm_source=linkedin_share&utm_medium=member_desktop_web
- [x] https://t.me/identity_on_eosio/525
- [x] https://eosioidwg.slack.com/archives/C01U0LEGNAF/p1660039731261939
- [x] https://t.me/HelloTelos/574480
- [x] https://discord.com/channels/892385699616153600/910223746533564436/1006511448563920946
- [x] https://discord.com/channels/722466006206906428/976895493244321843
- [x] https://t.me/pomelo_io/7408
- [x] https://t.me/EOSproject/1934566
- [ ] https://discord.com/channels/785124017430331392/818827209921658930
- [x] https://discord.com/channels/722466006206906428/971085405162209320/1007272193018822740

**Comment by theblockstalk** [comment]
https://pomelo.io/grants/recovery

**Comment by kamitor** [comment]
@stefan
We should have all the post scheduled for linkedin
We should decide who takes over the button pressing
We should have the materials ready

**Comment by justaklaus** [comment]
Pomelo grant posts and tweets are all set. On tweetdeck you can see the posts scheduled, and on linekdin on of the post was today and the other one can be of your choice. Picture to use is here:![Pomelo.png](https://images.zenhubusercontent.com/62c6e3b8e9de48565b9abf6e/32ebb380-5ed9-4d51-b9f8-96bb255f6137)
