### ISSUE TITLE
New Pitchdeck for website

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#11]
From https://tree.taiga.io/project/theblockstalk-tonomy-foundation/task/245 and https://tree.taiga.io/project/theblockstalk-tonomy-foundation/us/128?milestone=321022

Done

- [x] Create document with story outline https://docs.google.com/document/d/1FVMLswIFrwViXtONkrbt6kusdP_0JDNK8wDGC1-PV4A/edit
- [x] Review
- [x] Video draft
- [x] Review
- [x] Final video
- [x] Add to website

**Comment by Mrak1985** [comment]
Hi @adorablelealet
