### ISSUE TITLE
Create template to reach different customers, clients, collaborators

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#110]
**Description:**

Chris started to work on that https://docs.google.com/document/d/1mbhRnFr3GI2SUkXcWefIWcQcRcQnr7NPFV4JW4ynv2g/edit

Mike had created https://docs.google.com/document/d/1QCz3-WQSZPZEh8FqXqoVBL_x9388SxbOmn-AFG0ToSI/edit 
to reach out investors

**Definition of done:**

- [x] Investors email outreach is updated
- [x] Cold message for LinkedIn is created
- [x] Cold email to potential ambassador is created
- [x] Cold email for potential contributor is created
- [x] Cold email for potential collaborator/university/lab is created
- [ ] Review by 1 person and Yegor

**Comment by kamitor** [comment]
https://docs.google.com/presentation/d/1g1ZX7y6H3JtixmEdieMuzajHPosALIqzs89Qjj9rPwE/edit#slide=id.p

**Comment by kamitor** [comment]
Wow :D

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/1mbhRnFr3GI2SUkXcWefIWcQcRcQnr7NPFV4JW4ynv2g/edit

**Comment by Mrak1985** [comment]
3.5 Chris, 17.5 Mike
