### ISSUE TITLE
Announce on social media ENF grant submition

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/management#111]
Description

https://github.com/eosnetworkfoundation/grant-framework/pull/57
- we should also do some announcements of this when relevant, not yet - wait till they accept
https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md

Definition of done

- [x] write blog about that and do editing (with Yegor)
- [x] write LinkedIn post and Twitter or else if necessary and do editing (with Yegor)
-

**Comment by kamitor** [comment]
Templates for cold email
For followup
for closure
For HR

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/1rzKH1HsdHDrK3iIf_BxSB-c6cf7plOdWqV7rndODrz4/edit#

**Comment by Mrak1985** [comment]
![Tonomy Foundation.png](https://images.zenhubusercontent.com/62c6a6e69c59cc221bd21079/a20afe4b-9671-4522-9a3e-2c5082a5b28e)

**Comment by Mrak1985** [comment]
Sent to EOS Network foundation to check it

**Comment by Mrak1985** [comment]
Sent them another reminder

**Comment by Mrak1985** [comment]
create follow up task
