### ISSUE TITLE
Prototype video for Pomelo

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#113]
**Description:**

we need to finish our prototype video

**Definition of done:**

- [x] Video is created
- [x] Reviewed by Jack and Mike or Chris
- [x] Video shot one more time based on the above comments
- [x] Video submitted when it is required

**Comment by Mrak1985** [comment]
@theblockstalk I guess this is our link https://www.loom.com/share/e2d2378710fc4d0ba4d017f266f6607a?

**Comment by theblockstalk** [comment]
this one is better
https://www.loom.com/share/2ac4840393094f5a8c498313d5ce45c7

**Comment by Mrak1985** [comment]
> this one is better https://www.loom.com/share/2ac4840393094f5a8c498313d5ce45c7

this is unfortunate Jack as we have this link on Pomelo website https://www.loom.com/share/e2d2378710fc4d0ba4d017f266f6607a , can we change it if your version is better.

**Comment by kamitor** [comment]
It's there in Loom video// :)

**Comment by kamitor** [comment]
needs design
