### ISSUE TITLE
Twitter Spaces Rapid Fire (English)

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#116]
**Description:**

Are you a grant owner on the Pomelo.io crowdfunding platform? Sign up below to pitch your grant to the EOS community!

As an additional opportunity for Pomelo grant applicants to promote their project, we want to offer platforms to engage with the EOS community. Applicants will be emailed with further details.

Applicants must share their link to an approved grant to apply. Returning grant creators can share their Season 2 grant and new great creators from Season 3 must wait until they are approved to submit their pitch session application.

Twitter Spaces Rapid Fire (English)
 - Hosted live on Twitter Spaces
 - Pitch your project in 2 minutes and answer 1 question in 1 minute.
 - Thursday, August 11 at 16:00 UTC

**Definition of done:**

- [x] Pitch is ready
- [x] Pitch if needed to be reviewed
- [x] Pitch is performed

**Comment by theblockstalk** [comment]
this is on Wednesday 10th august - we will be invited

**Comment by theblockstalk** [comment]
We have been invited. 10th august at 6pm UTC (6pm Amsterdam time)

**Comment by theblockstalk** [comment]
We have also been invited for the Korean edition at 13:00 UTC on Thursday 11th

**Comment by theblockstalk** [comment]
Two minute pitch story:
- problems of useability and loosing accounts. what if you could invite your family and friends to use a secure sovereign wallet without them having to manage keys or worry about loosing their phone?
- tonomy ID crypto and SSI wallet
- whitelabeled for EOS, Telos and WAX
- social recovery, proposed by Buterin and now adopted in Ethreum ecosystem poorely
- how it works - choose buddies, loose phone, scan QR
- security. decentralized keys, no private keys ever stored on server, only one phone. no user even sees private keys. see our prototype video in the Tweet
- better than Ethereum, easier than Anchor
- massive onboarding potential, super easy for users. worldwide recognition for properly solving one of crypto's biggest problems

**Comment by Mrak1985** [comment]
@theblockstalk looks good, just try to pitch it and record necessary time - all those topics won't align in 2 mins right? So let's make it simple - fits for EOS, Telos, WAX, social recovery, cheeper than Ethereum and compatible at least, Those will be your 2 mins

**Comment by theblockstalk** [comment]
Two minute pitch story:
- what if I asked you to tell you had to invite all your friends and family to EOS, Telos or WAX today?
- what problems would they have?
- Tonomy ID crypto and SSI wallet focusing usability without any loss of security or sovereignty
- no need to know anything about private keys or blockchain
- whitelabeled for EOS, Telos and WAX
- social recovery, proposed by Buterin and now adopted in Ethreum ecosystem poorely
- how it works - choose buddies, loose phone, scan QR
- security. decentralized keys, no private keys ever stored on server, only one phone. no user even sees private keys. see our prototype video in the Tweet
- better than Ethereum, easier than Anchor
- massive onboarding potential, super easy for users. worldwide recognition for properly solving one of crypto's biggest problems

**Comment by kamitor** [comment]
@stefan 
We should have all the post scheduled for linkedin
We should decide who takes over the button pressing
We should have the materials ready

**Comment by kamitor** [comment]
Followup from Pomelo - Carrie - Euro's that we can use.
