### ISSUE TITLE
Tencent meeting on WeChat (Chinese or English) 

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#117]
**Description:**

Are you a grant owner on the Pomelo.io crowdfunding platform? Sign up below to pitch your grant to the EOS community!

As an additional opportunity for Pomelo grant applicants to promote their project, we want to offer platforms to engage with the EOS community. Applicants will be emailed with further details.

Applicants must share their link to an approved grant to apply. Returning grant creators can share their Season 2 grant and new great creators from Season 3 must wait until they are approved to submit their pitch session application.

Tencent meeting on WeChat (Chinese or English) 
 - Hosted by the EOS Nation Asia team.
 - An amazing opportunity to share your project with the Asian community! 
 - These pitch sessions are hosted in Chinese, but there is a translator present, so they are available to English-only presenters. 

**Definition of done:**

- [x] Pitch is ready
- [x] Pitch if needed to be reviewed
- [x] Pitch is performed

**Comment by theblockstalk** [comment]
> Hi Jack, of course, you will have 10-15 mins to introduce grant and 5-10 mins for Q&A.

**Comment by Mrak1985** [comment]
6th of August

**Comment by theblockstalk** [comment]
https://www.beautiful.ai/-N8cKOqRGjAacX2YFdZe/6

**Comment by kamitor** [comment]
20 stuff
