### ISSUE TITLE
Pomelo Pitch Sessions Korea Edition (Korean, English and Chinese)

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#118]
**Description:**

Are you a grant owner on the Pomelo.io crowdfunding platform? Sign up below to pitch your grant to the EOS community!

As an additional opportunity for Pomelo grant applicants to promote their project, we want to offer platforms to engage with the EOS community. Applicants will be emailed with further details.

Applicants must share their link to an approved grant to apply. Returning grant creators can share their Season 2 grant and new great creators from Season 3 must wait until they are approved to submit their pitch session application.

Pomelo Pitch Sessions Korea Edition (Korean, English and Chinese)
- Hosted live on Twitter Space 
- Hosted by the EOS Nation Asia team and Max from Eden Korea
- Pitch your project in 5 min and answer questions in 5 min.
- These pitch sessions are hosted in Korean, supportive of English and Chinese presenters.
- Thursday, August 4th at 13:00 UTC

**Definition of done:**

- [x] Pitch is ready
- [x] Pitch if needed to be reviewed
- [ ] Pitch is performed

**Comment by Mrak1985** [comment]
have not been invited, today

**Comment by Mrak1985** [comment]
@theblockstalk presentation is ready, You will have 5 mins only, so I kept 5 original slides and created 1 more, Also you will have 3 slides as a backup https://www.beautiful.ai/-N8cKOqRGjAacX2YFdZe/1

**Comment by theblockstalk** [comment]
ok, great we have the presentation. but we have not been invited to this event. please close the task @Mrak1985
