### ISSUE TITLE
Create Grant proposal for NLNET.nl which we used for NGI all 3 of them

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#119]
**Description:**

 https://nlnet.nl/useroperated  research and submit 3 grants for NLNET using those 3 for NGI and Azure

**Definition of done:**

- [x] Research grant condition
- [x] Create 3 proposals
- [x] All 3 are reviewed
- [x] Grants are submitted

**Comment by Carrie22022** [comment]
I think this is done.

**Comment by Mrak1985** [comment]
I see - this is different grants Carrie, but we can use the same bunch of grants from NGI. Different platform, same text

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/1hDU977X0KPBTfEXZI6MV1J60dhuYbFO0jgNGjlcodlI/edit
https://docs.google.com/document/d/1Zq0vPw5zhqblfmeeoWjYlV7tCbkzHsKrwgpfnpqycyA/edit#heading=h.q9nyd79i5ah2
https://docs.google.com/document/d/1sb1dEeMZR9kdF3clJlbXgYYMYKzd-Qk5fENaGfYVtZk/edit#heading=h.5n3pqjul68ug

**Comment by Mrak1985** [comment]
Requestor:	Jack
Email:	contact@tonomy.foundation
Applied all 3
