### ISSUE TITLE
Hire designer from the Students

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#125]
**Description:**

We need more contributors. Let's hire a designer from the Students who would work for tokens

**Definition of done:**

- [x] Interview based on our HR template was performed
- [x] Try to conduct the interview
- [x] if successful remove epic
- [x] If unsucessful schedule new task

**Comment by kamitor** [comment]
One potential interviewer

**Comment by kamitor** [comment]
Meeting Jacob again next tuesday

**Comment by kamitor** [comment]
Jacob

**Comment by kamitor** [comment]
Damn, Jacob says no, he can't commit the time. Gonna search more

**Comment by kamitor** [comment]
Damn, Jacob says no, he can't commit the time. Gonna search more
