### ISSUE TITLE
Respond to ENF comment about grant proposal

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#128]
**Description:**

When a comment is written, we have to respond to it

https://github.com/eosnetworkfoundation/grant-framework/pull/57

**Definition of done:**

- [ ] Respond is posted

**Comment by kamitor** [comment]
Ongoing: 2 reviews and approvals
Responding to comments, Still happening
Two more reviewers scheduled

if one of the reviewers approves it we will get 36000.
"can we rewrite this task as an epic and then create tasks that can be completed in the sprint (that is small enough, like sending a message) "
