### ISSUE TITLE
Tonomy management backlog

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#133]
Description:

Springt from 16 Aug 22 - 30 Aug 22

Definition of done:

- [x]  Tonomy Management product backlog in Zenhub is organized, prioritized and with definition of done in all tasks by the start of sprint planning meeting
- [ ]  meeting with marketing
- [ ]  meeting with finance
- [ ]  meeting with HR
- [ ]  meeting with Development
- [ ]  meeting with Projects

**Comment by kamitor** [comment]
Mike had added new tasks
We now have a chat channel in new task
New ticket for things that are stuff is missing
Track for expenses -

**Comment by kamitor** [comment]
We are lacking HR, we are lacking Finances still. Nothing extra, working on the grants. 
We need a financial group, meet during the sprint. 

><>> New tasks: > Finance discussion needed 
> New Tasks: > Meetup with Marketing
> New Tasks.
