### ISSUE TITLE
Social media content creation for 16-30 Aug sprint

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#134]
Description:

We have to create and post some material on our social just to show that we are alive more or less

Definition of done:

- [x]  4x Tweets posted
- [x]  2x Linkedin posted

**Comment by Mrak1985** [comment]
1 LinkedIn was posted https://www.linkedin.com/feed/update/urn:li:activity:6965673100117991424

**Comment by Mrak1985** [comment]
1 more linkeind post https://www.linkedin.com/feed/update/urn:li:share:6968575124572655616?utm_source=linkedin_share&utm_medium=member_desktop_share&utm_content=post

**Comment by kamitor** [comment]
<3 <3

**Comment by kamitor** [comment]
Aymen added the fact that we're badly visible on the net still
