### ISSUE TITLE
EOS converted to Dollar / Euro to pay expenses in.

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#136]
**Description:**

When Pomelo grant is finished, we withdraw Pomelo EOS tokens to Jack's account and then convert it you fiat

**Definition of done:**

- [x] EOSs are withdrawn
- [x] Jack or other person converted them if needed to fiat

**Comment by Carrie22022** [comment]
There was some pre-work done here to be able to start the tasks listed above. I confirmed that the EOS direct donations have been automatically transacted to the Tonomy account. The matching is still undergoing analysis and there should be a report (along with the EOS automatically transferred) when the analysis is complete.

![image.png](https://images.zenhubusercontent.com/62b349b8245ec313edcf1042/0387e89f-4cf8-4e07-b571-1a4de67f671b)

**Comment by theblockstalk** [comment]
I have done this for the deposited EOS, it's now in Coinbase in Euros

deposit to Binance
https://bloks.io/transaction/583321508bb446c6aa0fc8ce3069fe022306a1c5583cd5ce7bbba23816c5afe7

withdrawal from Binance
https://bloks.io/transaction/3ce1a64a9c138e8dccf227ad61ff867a87ab5dda79715b457cb4fd3e0b6c8a18

deposit to Coinbase
https://bloks.io/transaction/6d38f003c59dc3306ce64c6d5eaf255d97b8047ec7e8f9c0e645153f083f0ea1

**Comment by theblockstalk** [comment]
€916.88 Euros

**Comment by Mrak1985** [comment]
> Cool, not bad

**Comment by kamitor** [comment]
Half the grant
The matching is still to be matching. 

>> tasks has already been created
