### ISSUE TITLE
Full draft of Telos grant proposal

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#138]
https://ignite.telos.net/

Definition of done:

- [x] Create full draft of Telos grant

**Comment by theblockstalk** [comment]
other option is through Telos Decide
https://app.telos.net/trails/ballots

**Comment by theblockstalk** [comment]
setup
https://docs.google.com/document/d/17j3j0ST6-lKr92EgFtjtVajNRPv2Zm3B5_1TjfgAb4Q/edit#

**Comment by Mrak1985** [comment]
Reviewed

**Comment by theblockstalk** [comment]
calculation for what we would need to do, to make feasibility study
https://docs.google.com/spreadsheets/d/1W9QiMnEsbenxrNGTus4AW61EQ_-lOUtZ72HuAieil1s/edit#gid=0
