### ISSUE TITLE
Finalize and submit Telos proposal

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#139]
Definition of done:

- [x]  Take feedback from review
- [x]  Finalize proposal
- [ ]  Submit proposal

**Comment by kamitor** [comment]
Upcoming sprint should be committed to.

**Comment by theblockstalk** [comment]
proposal for Telos Decide:
https://docs.google.com/document/d/17j3j0ST6-lKr92EgFtjtVajNRPv2Zm3B5_1TjfgAb4Q

**Comment by theblockstalk** [comment]
currently getting an error in the Anchor wallet when trying to submit, cannot resolve.
https://t.me/c/1139062279/315926

**Comment by theblockstalk** [comment]
still blocked
https://t.me/TelosWPS/24857

**Comment by theblockstalk** [comment]
submitted! can be viewed with the TElos Decide mobile app
https://mainnet.decidevoter.app/works/milestone?proposal_name=yohqqqppkkpl&milestone_id=1

**Comment by Mrak1985** [comment]
@theblockstalk could be cool to have a video or a picture as an evidence
