### ISSUE TITLE
Hire designer

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#142]
**Description:**

We need more contributors. Let's hire a designer from the Students who would work for tokens

**Definition of done:**

- [x] Made a post about hiring on LinkedIn and other resources if needed
- [x] Screening aproprieate candidates or companies
- [x] Interview based on our HR template was performed
- [x] In case of successful interview above, give offer to the designer if not successful repeat another interview

**Comment by theblockstalk** [comment]
I'll be making an add on Freelancer.com, mayber fiver as well

**Comment by theblockstalk** [comment]
great input from my friend Jesse
https://www.notion.so/tonomy-foundation/320602f5422949a2b814465a5e9354c2?v=6d5b01f1cf4f443cbd519a61c6a20fe6&p=8517e17a912e403e9084f44dfdd46a03&pm=s

**Comment by theblockstalk** [comment]
post made in freelancer
https://www.freelancer.com/projects/mobile-app-testing/High-fidelity-design-Identity-wallet/proposals

**Comment by theblockstalk** [comment]
interviews done
https://www.notion.so/tonomy-foundation/320602f5422949a2b814465a5e9354c2?v=6d5b01f1cf4f443cbd519a61c6a20fe6&p=57516ca297084931b4ec92eb9cab7a9f&pm=s

**Comment by theblockstalk** [comment]
chosen, and onboarding meeting setup
https://www.notion.so/tonomy-foundation/320602f5422949a2b814465a5e9354c2?v=6d5b01f1cf4f443cbd519a61c6a20fe6&p=a35ba6ceee4f4a519e71dc0749597b40&pm=s
