### ISSUE TITLE
ChefChef grant evaluation

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#143]
**Description:**

Have to figure out what to do for ChefChain grant [https://app.zenhub.com/files/510762397/1d9ba606-6dcd-4ac8-934b-bafbce0491ef/download](https://app.zenhub.com/files/510762397/1d9ba606-6dcd-4ac8-934b-bafbce0491ef/download)

**Definition of done:**

- [x] - align the parties on what each provides
- [x] - evaluate what we can do and whether it aligns with our goals
- [x] - calculate the cost from Tonomy to do this
- [x] - make a final call on whether we can do it for the budget

**Comment by kamitor** [comment]
https://docs.google.com/document/d/1Ct9091KxQJUYDAIKvsqFttNu23w1W3Zl/edit?usp=sharing&ouid=110337144130237447952&rtpof=true&sd=true

**Comment by kamitor** [comment]
Facilitate meet between Fork & Chef & and Tonomy

**Comment by kamitor** [comment]
Calculation was 150K so we have to renegotiate

**Comment by Mrak1985** [comment]
@kamitor we need calculation for Tonomy how much resources we will have to spend for this grant and clear output of this
