### ISSUE TITLE
Social media content creation for 30-13 Sep

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#145]
Description:

We have to create and post some material on our social just to show that we are alive more or less

Definition of done:

- [x]  4x Tweets posted
- [x]  2x Linkedin posted

**Comment by justaklaus** [comment]
Visuals are made

**Comment by Mrak1985** [comment]
https://twitter.com/TonomyF/status/1567824230867255296?s=20&t=Fsycv-j6KjwppvKZK9SiIQ
https://www.linkedin.com/feed/update/urn:li:activity:6973581067182067712

**Comment by Mrak1985** [comment]
https://www.linkedin.com/feed/update/urn:li:activity:6975423157193052160

**Comment by Mrak1985** [comment]
Need some points for Stefan, Anna, Yegor
