### ISSUE TITLE
EOS converted to Dollar / Euro to pay expenses in from the Pomelo grant - the rest 900 EOS coins

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#147]
When Pomelo grant is finished, we withdraw Pomelo EOS tokens to Jack's account and then convert it you fiat

Definition of done:

 

- [x] EOSs are withdrawn
- [x] Jack or other person converted them if needed to fiat

**Comment by theblockstalk** [comment]
still waiting on ENF processing

**Comment by theblockstalk** [comment]
deposit:
https://bloks.io/transaction/ee116501cc9d0476c92d9e59035e09ce636bf815bcbfac3cc597afd0d2d6df00

converted to €1056.61
