### ISSUE TITLE
Create expense tracking document for all employees

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#148]
**Description:**

We need to have a document or some open source software where we can track our Tonomy's expenses. We have to remember though that when we spend our money and are not repaid back, we get 100% Tonomy coins (TMYCON) on top of the amount spent (1 coins is about 1 euro and 1 euro in addition). EG you pay 10 euro for Notion subscription, if no payment back at the end of the month, you get 20 TMYCON. When we will be able to pay you back, you get 10 euro, pay back 10 TMYCON and keep 10 TMYCON to exchange in the future. 

Also good reminder that we need to support opensource technology, so it is always to use it as a service (if it is free especially)

**Definition of done:**

- [ ] Expense tracking document is created or software is chosen

**Comment by Mrak1985** [comment]
https://www.freshbooks.com/pricing
https://www.fylehq.com/pricing
2 pieces of software best in their segment

**Comment by theblockstalk** [comment]
have used freshbooks before, pretty good

**Comment by theblockstalk** [comment]
https://www.moneybird.com/

**Comment by Mrak1985** [comment]
We will use freshbooks software, as it seems to be pretty good
