### ISSUE TITLE
Task for bonding with other teammate (multiple people) (Sprint starting October 11)

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#155]
We need to create some bonding in our team.

Work together for an hour. Pair programming or in whatever task you are doing.

Definition of done:

- [ ]  Working together was done.
- [ ] Put a small message on Rocket Chat (Twitter/Linkedin for +3 points) that you worked together, what you did and what you liked about it

**Comment by kamitor** [comment]
Aymen and I will be setting up the discord together :) 12 okt.

**Comment by Mrak1985** [comment]
@kamitor it is not task to work together, but to bond)

**Comment by Mrak1985** [comment]
Talked to Aymen for 1 hour
