### ISSUE TITLE
Research the UAE innovation grants

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#161]
**Description:**
https://www.mbrcgi.gov.ae/en/home

- What is the purpose/reason for this task?
To get funding from the UAE as the inclined towards new technologies for government 
- What current or future goal of the TF does it help achieve?
Aligning with those grants will let Tonomy to achieve its goals for building ecosystem of trust

**Definition of done:**

- [ ] Research is done 
- [ ] Lists of grants performed and added to the grant list https://docs.google.com/spreadsheets/d/1ZScGmG5sNVsQGpcvYQq8_k55dFlfgvFWsLiZm5-tKsU/edit

**Comment by YegorTDK** [comment]
the grant proposal might not be available, sent out an inquiry letter

**Comment by YegorTDK** [comment]
The grant proposal is no longer available. Apparently, they have no other programms, since they didn't text back
