### ISSUE TITLE
Research how to be a part of OECD

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#162]
**Description:**
https://oecd-opsi.org/blog/innovation2021/

Deadline is 5th of September

- What is the purpose/reason for this task?
Looking for new opportunities to promote Tonomy
- What current or future goal of the TF does it help achieve?
We can align with other projects and will be well known as well

**Definition of done:**

- [ ] Research is done

**Comment by theblockstalk** [comment]
@YegorTDK what did you do here and why should we close or not close this task?
