### ISSUE TITLE
Follow up with Claire to talk to Jamie about what else they could do - Jack to ask her about that

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#163]
**Description:**

- What is the purpose/reason for this task?
To get an insight
- What current or future goal of the TF does it help achieve?
Will bring potential opportunities for Tonomy

**Definition of done:**

- [ ] The talk was made and some Notes are written

**Comment by theblockstalk** [comment]
best shot for Blog = after November
I ask her about this, and again due to their internal policy with new ministerial things, suggests we do after November for anything. Does not want to ask Jamie about this till after then.
No other suggestions.
