### ISSUE TITLE
Agree on the governance strategy for Tonomy

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#168]
**Description:**

- What is the purpose/reason for this task?
To have a clear vision how to rule and collaborate inside Tonomy
- What current or future goal of the TF does it help achieve?
To be more efficient and productive

**Definition of done:**

- [x] Final government strategy is accepted and shared with everyone

**Comment by theblockstalk** [comment]
Creating summary of our strategy here
https://www.notion.so/tonomy-foundation/Projects-houses-d3cb1f02ab334a749725aa7a437ff955?p=f9b29d043b254d88950b83d3946eed56&showMoveTo=true

**Comment by Mrak1985** [comment]
@all Yesterday management team discussed again the details of our SCRUM process, specifically the division between the growing internal team committed to working with us most days of the week, and advisor/contributors who are able to contribute but in a less reliable way.

Everyday contributors are expected to join our existing SCRUM process, including all of the rituals on the days they work:

standup @ 3:30pm
review @ 2nd Tuesday
retrospective @ 2nd Tuesday
planning @ 2nd Wednesday
If you can't join on specific day please let us know. @Robert @Anna @aymen @rebal @chris @Mike @theblockstalk @Yegor

Advisor/infrequent contributors are not expected to join any meetings, but we have the following expectations

You join the beginning part of the review ritual @ 2nd Tuesday to show what you have done. Advisors will go first and can leave after their demo. If you cannot join, then send a video demo of what you have done before the meeting .
During the planning ritual we will assign 1 or more tasks to you based on their judgement. The product owner @Mike / @theblockstalk expected gather your expected commitment (story points) before this meeting and assign you to task they think you would be able to do. The PO should also give you a chance to have a call with them to go through the tasks.
The SCRUM master should infrequently follow-up with you during the sprint to gather your progress. @Mia @Carrie @Stefan @Suneet
