### ISSUE TITLE
Ask Jack and Mike to update their expenses

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#169]
**Description:**

- What is the purpose/reason for this task?
To be updated with expenses
- What current or future goal of the TF does it help achieve?

**Definition of done:**

- [x] Jack updated his expenses
- [x] Mike updated his expenses

**Comment by theblockstalk** [comment]
https://docs.google.com/spreadsheets/d/1cFT4Z02ORqhu9qXK7bCGahq7CNmirgZShzpKpD94t-Y
