### ISSUE TITLE
Review software licenses

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#170]
**Description:**
have somebody review software licenses and then for the team to make an informed decision about what open source licence we apply to our software is.

https://choosealicense.com
- What is the purpose/reason for this task?
- What current or future goal of the TF does it help achieve?

**Definition of done:**

- [ ] Licenses are reviewed and proper is chosen

**Comment by theblockstalk** [comment]
PS there is a good list of definitions of the different clauses of open source licenses at the end of this page:

https://choosealicense.com/appendix

**Comment by theblockstalk** [comment]
May also be worth considering broadly how different open source software business models work, or more specificity how Software as a Service works
https://duckduckgo.com/?q=open+source+business+models&t=brave&ia=web

**Comment by Robbort97** [comment]
Drew advises to use apache 2.0 as well
