### ISSUE TITLE
Create procedure for hiring new freelance members to Tonomy

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#172]
**Description:**

- What is the purpose/reason for this task?
Rebal is hire so we need to sign a contract : we need to know how to hire people effectively under a foundation
- What current or future goal of the TF does it help achieve?
He will feel dignity, insurance that he will get his salary. On top of that, it  will give us a template for others employees

**Definition of done:**

- [x] There is a *draft* procedure created in the form of a powerpoint presentation or on Notion (A word document is *not* acceptable) 
- [ ] Mihail and Chris have both reviewed this procedure and can understand it, you check this by letting them preform a LSD action. (Luisteren Samenvatten Doorvragen) You can trigger this by asking " could you explain how you see this in your own words?" 
- [x] The legal implications, Risk to our foundation, Costs associated with it, legal binding have been considered
- [x] The procedure must include the Intellectual Property volunteer rights transfer as part of it's process (either a check if it's there or strait up requirement)

**Comment by kamitor** [comment]
Attempting Handover to Robert

**Comment by Mrak1985** [comment]
@Robbort97 can you please add evidence here as it is written in definition of done?

**Comment by Robbort97** [comment]
@Mrak1985 @kamitor this is the draft version https://docs.google.com/presentation/d/1SCK7OtOBzzQeKOfCbwJ9hVqpFO5t09A313yTQWsS9gE/edit#slide=id.p
