### ISSUE TITLE
SEO for the website

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#174]
**Description:**

- What is the purpose/reason for this task?
Tonomy is not very visible on the internet
- What current or future goal of the TF does it help achieve?
To let people find Tonomy website easier, and it will give better acknowledgement

**Definition of done:**

- [ ] SEO was set and it is

**Comment by mertkama** [comment]
What is the purpose/reason for this task?

Extracting content for the word "Tonomy" is important for SEO work. But on its own it won't matter. It should be structured with other words that stand out more in competing niches. Thus, SEO will result in more successful results.

**Comment by mertkama** [comment]
What current or future goal of the TF does it help achieve?

I can continue this topic as follows;

https://medium.com/@prestonwallace/3-ways-improve-react-seo-without-isomorphic-app-a6354595e400

I found an article here that gives very effective and accurate results, please everyone take a look at it.

1.Content, Optimized for your Keywords
2.Domain Name and Age
3.Page Speed and Mobile Friendliness
4.Inbound Links
5.An Accessible URL
6.Technical SEO (Title, Meta Tags, Image Alt Tags)
7.Content Viewable By Search Engines (i.e. Google can crawl your pages)

"Accessible URL",
"Technical SEO",
  and making your site :
"Googlebot" Friendly.

**Comment by mertkama** [comment]
I also found another article about which one we need between CSR and SSR;

Take a look at this too.

https://theamanverma.medium.com/what-is-csr-ssr-in-react-14bc3ea2ca32


There are two issues that need to be investigated in this regard;

React.js = CSR
Next.js = SSR

My opinion is to proceed with React and install an SEO package in it, to try it first.

**Comment by Mrak1985** [comment]
@mertkama Ibrahim, you just need to set SEO for current wordpress website. You can ask Chris for Login and password
