### ISSUE TITLE
Hire a designer

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#176]
Description:

We need more contributors. Let's hire a designer from the Students or else who would work for tokens
Use this folder to contact applied people with warning that it is a volunteer position with further potential to get paid

Definition of done:

 

- [ ] Try to conduct the interview
- [ ]  Interview based on our HR template was performed
- [ ]  if successful remove epic
- [ ]  If unsuccessful, schedule a new task

**Comment by kamitor** [comment]
We might already have a designer amongst us but we just don't know

**Comment by Mrak1985** [comment]
@kamitor do you really think we should close it based on this ground that we might not know?))) I thought a designer with a certain level

**Comment by Mrak1985** [comment]
Has contacted those people in the folder https://drive.google.com/drive/u/3/folders/1POxCL0AHvOwK1c9lxniny7WNjxMuiYKM through email and Linkedin asking to answer in video some quesions

**Comment by Mrak1985** [comment]
![image.png](https://images.zenhubusercontent.com/62c6a6e69c59cc221bd21079/eb604633-ff6c-4b13-a9b7-f411cf795f35)
No one has replied. Will create a new task and make a post on LinkedIn
