### ISSUE TITLE
 Cut from the review meeting the explanation of jack what he has build last sprint at 16:00 - 16:50 

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#177]
put into a video and post

https://www.loom.com/looms/folders/Technical-794473cc2ae04d89b19a37268174dad2

**Comment by Mrak1985** [comment]
@justaklaus @AnnaLotukhova  this is the folder with technical stuff from which you can make some video. 2 links, both can be good.

https://www.loom.com/looms/folders/Technical-794473cc2ae04d89b19a37268174dad2

https://www.loom.com/share/8566b834759742309ebc96c74e955767

**Comment by justaklaus** [comment]
I checked the videos and from my point of view, I would just leave them as is and upload them on YouTube or which ever video based platform. Creating the thumbnail would be the only thing to do. The videos seem to be just going through things with not a lot of structure that would make a special type of video. But bare in mind this is coming from someone who doesn't understand it, with some guidance there might be something to make

**Comment by Mrak1985** [comment]
New post. I gave it to Yegor to check for grammar

How we work
Meanwhile, we would like to show for interested in blockchain #programmers how our Lead architect and cofounder explains the process of creating Tonomy ID. It is only 8 minutes but we record such short videos as we all work remotely for Tonomy which is one of many benefits. We are creating the Ecosystem or digital country where based on the blockchain we will collaborate transparently as to give an opportunity to society to cease corruption and inequality. You can join us as a developer or else if you see how you can contribute to our product. We have 14th people currently and in the process of hiring more to boost our development and bring our product earlier. Currently, developing Tonomy ID which can widely used in keeping medical and education records, using for know your client technology, signing contracts - those business cases we will show you in the next posts. Join us to smartly 
 make our world a better place  

https://www.loom.com/share/8566b834759742309ebc96c74e955767

**Comment by Mrak1985** [comment]
https://www.linkedin.com/feed/update/urn:li:activity:6973581067182067712

We have made the post, @AnnaLotukhova will get 3 points, @justaklaus  4 points as he had to create post, Mike for posting and reviewing 3, @YegorTDK  3 for Editing. Everyone is happy with points? They do not matter actually, I am happy that we have done this work together
