### ISSUE TITLE
Review ENF grant and understand what we will need to do to complete first milestone

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#181]
**Description:**
Review ENF grant
https://github.com/Tonomy-Foundation/EOS-network-foundation-grant-framework/blob/ssi-toolkit/applications/ssi-toolkit-verifiable-credentials.md

- What is the purpose/reason for this task?
We have to understand what this grant about and which resources do we need
- What current or future goal of the TF does it help achieve?
To receive money

**Definition of done:**
People to review and write down resources (not necessary all people)
- [ ] Chris
- [x] Mike
- [x] Rebal

**Comment by Mrak1985** [comment]
I guess we need to create tasks based on the grant to get those money so we can pay to our developers

**Comment by Rebal67** [comment]
I reviewed it's achievable, but we need to have nodes as fast as possible to test that end to end and on multiple phones. also to create scrum environment (mistake friendly) a server where u can test things freely without breaking anything.
