### ISSUE TITLE
Onboard new people into Tonomy in such a way that they can pick up a task in the Tonomy board in the next sprint

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/management#183]
- [x]  Check CV's are in the correct folder
- [x]  Show the onboarding in Notion
- [x]  Onboard on all our tools
- [x]  Show the zenhub board and how it works
- [x]  Explain Scrum process

**Comment by Mrak1985** [comment]
Anna's onboarding
https://www.notion.so/tonomy-foundation/2022-09-06-Onboarding-with-Anna-6e203a23c17349ad8b59d39b9077464b
