### ISSUE TITLE
Onboard new people in Tonomy in such a way that they can pickup tasks starting the next sprint

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/management#184]
- [x] Check CV's are in the correct folder
- [x] Show the onboarding in Notion
- [x] Onboard on all our tools
- [x] Show the zenhub board and how it works
- [x] Explain Scrum process
- [ ]

**Comment by Mrak1985** [comment]
https://www.notion.so/tonomy-foundation/320602f5422949a2b814465a5e9354c2?v=6d5b01f1cf4f443cbd519a61c6a20fe6&p=0217aaa3c2364052af04cf49f5c0124b&pm=s
