### ISSUE TITLE
Create official document for loans 

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#185]
**Description:**

- What is the purpose/reason for this task?
To state clearly what is expected to be loaned and on what condition
- What current or future goal of the TF does it help achieve?

**Definition of done:**

- [x] research if this is legal
- [x] draft SIMPLE LEGAL document is created which stipulates the condition here

https://www.notion.so/tonomy-foundation/2022-08-17-strategic-meeting-715b817ab90e42da82a2029c21f1b4fd#dc9077edd60b4c1497470cffb2e89443

Follow up after this task
- legal check
- agreement and execution by foundation and loanees

**Comment by Robbort97** [comment]
https://docs.google.com/document/d/1cp7cpYL2fulfAm5WXAS-QseqINRuj7dYuOxp-V81u0Q/edit

**Comment by Robbort97** [comment]
@theblockstalk @kamitor please review this and if you agree with it or if I need to add anything else
