### ISSUE TITLE
Chefchain grant writing help

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#187]
**Description:**

- What is the purpose/reason for this task?
give help to Chefchain not to lose the opportuinity
- What current or future goal of the TF does it help achieve?
Get funding

**Definition of done:**

- [ ] help is provided and grant is written

**Comment by kamitor** [comment]
They Filed the grant :)

**Comment by Mrak1985** [comment]
I guess we did not help at all. Noone gets thos points
