### ISSUE TITLE
Legal documents for Tonomy ID

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#192]
For the European zone
Done:
- [x] Terms and conditions choosing template, review and create draft
- [x] Privacy noticing choosing template, review and create draft or choose a temp

**Comment by Robbort97** [comment]
I have a template for both and am now reviewing them.

**Comment by Robbort97** [comment]
EULA: https://docs.google.com/document/d/12fnL_i-dnIvloHEz0JfoA5Ydsabhg3FK_-EVAMJPyhg/edit#

**Comment by Robbort97** [comment]
Privacy policy: https://docs.google.com/document/d/1l3CTXxV5oF3DQBsRNMf4srdhzsDflZRUL2rlxuffogc/edit#

**Comment by Robbort97** [comment]
I'm blocked on the IP part of the EULA, since this goes hand in hand with the IP agreement. So as soon as I have done task #291 I can complete this as well.
