### ISSUE TITLE
Service level agreement\contract template

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#193]
for Software as a Service for Tonomy ID

This is the agreement we make we clients that pay us to run Tonomy ID with them.
https://cofes.com/saas-sla/

Done:
- [x] Contract draft is ready

**Comment by theblockstalk** [comment]
probably good to have this first
https://github.com/Tonomy-Foundation/Tonomy-ID-Management/issues/1

**Comment by Robbort97** [comment]
https://docs.google.com/document/d/1shhObxwmZJ55vkJRO8Dpd5HDId8dUyzfMqSuRYPS-58/edit

**Comment by Robbort97** [comment]
Made the contract, just needs information from the client

**Comment by Robbort97** [comment]
https://docs.google.com/document/d/1shhObxwmZJ55vkJRO8Dpd5HDId8dUyzfMqSuRYPS-58/edit

**Comment by Robbort97** [comment]
https://docs.google.com/document/d/1y-_eAPJmhAUFQZmVfrJwJMlvgCjhyK9sS3pd4aeZsHg/edit

Made a draft with some comments. @theblockstalk @Mrak1985 @kamitor can you take a look and let me know what you think? I'm stuck on point 6.
