### ISSUE TITLE
Update logo design

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#194]
Description:

Design iterations, team voting, and workshop for final discussion
https://drive.google.com/file/d/1D4jWjQXh_wrwF3If01JpuCwgxmzzeN7I/view?usp=sharing

Definition of done:

- [x]  final design is chosen

**Comment by Mrak1985** [comment]
@MilicaSequeira can you please express your opinion about Tonomy logo and if we keep it, let's close the tasks, otherwise we shall create a new design a logo

**Comment by MilicaSequeira** [comment]
I think its great and should be kept. I have an issue with the brand color if anyones asking. Any one of these would be classier/modern pick an adjetive.
![Screenshot_20230104_141732_Pinterest.jpg](https://images.zenhubusercontent.com/6391a6cc0faa24ff1a1a9c95/ba158177-7690-49f3-bd11-53dc55028e99)![Screenshot_20230104_141759_Pinterest.jpg](https://images.zenhubusercontent.com/6391a6cc0faa24ff1a1a9c95/a351efed-54ed-4fae-af6b-795e2bc86a5c)

**Comment by theblockstalk** [comment]
from @harpreet4singh 

> I have gone through the logo and I feel that the more or less, the logo direction and structure is correct (the symbol) but colors are not that great. We can maybe try some of the options with shade of blue/purple to see what works best when used in larger persective (for example, on website or mobile app). That will give us much clarity on the overall look and feel.

**Comment by Mrak1985** [comment]
create follow up task for @MilicaSequeira to may be change and implement colors as she thinks is right
