### ISSUE TITLE
Chris to update their expenses

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#199]
What is the purpose/reason for this task?
To be updated with expenses
What current or future goal of the TF does it help achieve?
Definition of done:

https://docs.google.com/spreadsheets/d/1cFT4Z02ORqhu9qXK7bCGahq7CNmirgZShzpKpD94t-Y
- [x]  Chris updated his expenses
- [x]  Jack updated his expenses - 3 points
- [x] Mike updated his expenses - 1 point

**Comment by Carrie22022** [comment]
No expenses for me.
