### ISSUE TITLE
Consider replacement for Notion

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#2]
Description:

Notion is our wiki tool. It is closed source and costs a lot. This task would be to replace this with a usable, open source and cost-effective tool. This can help us be transparent and stay aligned with our open source goals.

Definition of done:

- [x]  Check out https://hedgedoc.org/
- [x] Checkout https://alternativeto.net/software/codimd/
- [x] https://joplinapp.org/
- [x] https://hackmd.io/pricing
- [x] https://www.appflowy.io
- [x] Document prepared with list of options and pros and cons
- [x] Board votes on a new platform to replace Notion

**Comment by theblockstalk** [comment]
Ideas:
1. https://hackmd.io (Ethereum Foundation uses this)
2. https://www.appflowy.io

https://alternativeto.net/software/notion/?license=opensource

**Comment by kamitor** [comment]
1's gonna cost us, as its per user per month.

another good alternative would be 241
TiddlyWiki

I like it
 Gonna try running instance on dev server

**Comment by Mrak1985** [comment]
Document is here
https://docs.google.com/document/d/1kUcmT1XunQCu_rxZgzS7ZaV73YN6gj79paXEa5CFqkA/edit

**Comment by theblockstalk** [comment]
Great job!

@Mrak1985 I see you did not review https://www.appflowy.io I checked it out a few months ago and still not quite as mature as needed, but looks like its going in a great direction!

@kamitor I have tried Tidiwiki and AFAIKT, has no suitable team collaboration features.

I know the interface is not quite as easy as notion, but I think HackMD is a real option we could use. It delivers on everything else very well. We can pay for it now and self-host it later.

**Comment by theblockstalk** [comment]
oh sorry, I see appflowy now

**Comment by Mrak1985** [comment]
@theblockstalk Can you finish this up please as you better understand this task I guess

**Comment by theblockstalk** [comment]
I think there is 1 viable option from those reviewed: HackMD

I think @kamitor should try it and then we can discuss and vote on a change in the next meeting

**Comment by Mrak1985** [comment]
@theblockstalk ok, let's @kamitor to taste it. I don't like any of them and prefer to use free one

**Comment by Mrak1985** [comment]
Based on the meeting we downgraded Mike and Chris from Notion owner to save some money and when our server is ready, we can use CodiMD to make it more efficient
