### ISSUE TITLE
Hook up our Twitter to tweet / linkedin post by Zappier

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#205]
**Description:**

- What is the purpose/reason for this task?
To have easier way to post
- What current or future goal of the TF does it help achieve?
Save time for posting and reviewing posts

https://zapier.com/apps/rocketchat/integrations/twitter

**Definition of done:**

- [x] Hook up is done

**Comment by Mrak1985** [comment]
@Xdsylar Dylan, any progress on this task? Can you make some updates in the comments please?

**Comment by Xdsylar** [comment]
completed linkup, message shown in made channel

**Comment by Xdsylar** [comment]
only thing i need is to make the message the linkup gives perfect and test if the url works when tonomy posts a new tweet

**Comment by Xdsylar** [comment]
for the rest is everything done

**Comment by Xdsylar** [comment]
@Mrak1985  yeah my bad, i completely forgot to post updates here on github. i did complete the task only need to work on the finishing touches

**Comment by theblockstalk** [comment]
maybe do the same our linkedin
