### ISSUE TITLE
Follow up with Torben about 20-25th Sept

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#206]
**Description:**

- What is the purpose/reason for this task?
Potential partnership
- What current or future goal of the TF does it help achieve?

https://tonomyfoundation.rocket.chat/channel/Partnerships-houses?msg=TKJvcxxJEqD3HoxSc

**Definition of done:**

- [x] Meeting was performed

**Comment by theblockstalk** [comment]
done
https://www.notion.so/tonomy-foundation/320602f5422949a2b814465a5e9354c2?v=6d5b01f1cf4f443cbd519a61c6a20fe6&p=683dfed38d5e410a9b6e8be11c73ef10&pm=s
