### ISSUE TITLE
Hosting Marketing workshop Part 3

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#211]
Description:

https://docs.google.com/document/d/1sV7OoKbY4s1V1jaCtmCJjJVa3JB3CvsqJjHh2D80ewM/edit

We have to go through marketing workshop with all interested contributors and decide what our marketing strategy is

Definition of done:

- [ ] Necessary preparations are ready (if you were not part of the workshop, you need to review previous workshops including asking some questions)
Workshop 1 https://www.loom.com/share/f2e9a8a90d7245a59041864e624ef3fb
Workshop 2 https://www.loom.com/share/a77777f2bbe247c5977dbf192407e533
- [ ] Marketing workshop was done
- [ ] Created some personas from 2 to 5

**Comment by kamitor** [comment]
Making a datum prikker

**Comment by kamitor** [comment]
Tried and failed

Will send new datumprikker
