### ISSUE TITLE
Answer the following questions

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#212]
**Description:**

Then we will be able to pitch on a radio talk-show session at a place in Amsterdam.
I maybe have room to pitch what you are working on for Pakhuis de Zwijger. 

So can you explain me these following questions and can you sent me a website so I can read in to it? 

In what sense does your technological solution improve democracy?

How does the application works for either direct democracy or representative democracy?

What’s the added value for the democratic process? Why should it be a technological solution? 

And how would this translate for National gouverments and for a city like Amsterdam?

- What is the purpose/reason for this task?
Get 
- What current or future goal of the TF does it help achieve?

**Definition of done:**

- [x] Answers are prepared

**Comment by AnnaLotukhova** [comment]
https://docs.google.com/document/d/12WQ8MC9PE8nl-k2YdZiegcz6eUKoZwdFoczMK9uazKU/edit
