### ISSUE TITLE
To create a plan and tasks for New website Epic

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#215]
**Description:**

- What is the purpose/reason for this task?
- What current or future goal of the TF does it help achieve?

**Definition of done:**

- [ ] Plan is ready
- [ ] Tasks are ready

**Comment by mertkama** [comment]
1)

-You can get a section suggestion that is missing on the old website but to be added to the new website.

-Competitor analysis can be done transparently and distinctly.

- The parts of the website that attract the attention of the users who log into the competitor's website can be marked and they can be discussed with the team.

2)
-It can help to create a fast mobile compatible website.

- It can prevent users from having problems with speed when they first enter the website.

-When users enter the website, they can have precise and clear information about TF.

**Comment by Mrak1985** [comment]
Max, Dylan and Bas get 13 points each as for Onboarding, course passing and starting the plan
