### ISSUE TITLE
Social media content creation for 13-27 Sep

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#217]
Description:

We have to create and post some material on our social just to show that we are alive more or less

Definition of done:

- [x] Visuals are created
- [x]  Tweets posted
- [x]  Linkedin posted
- [x] Content social media document is updated

**Comment by AnnaLotukhova** [comment]
https://docs.google.com/spreadsheets/d/1dkINqaA5maMgZjT-dUG40RpP9A6jFyqUor2YCbN7c3k/edit#gid=762749088

**Comment by Mrak1985** [comment]
20 Stefan, 14 Anna, 5 Yegor, 1 Mikhail
