### ISSUE TITLE
To check how Rebal can apply or be eligible for the innovation tax benefit

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#223]
**Description:**

- What is the purpose/reason for this task?
To let Rebal get more salary

- What current or future goal of the TF does it help achieve?
Other employees in the future can follow the same path to get more money

**Definition of done:**

- [x] Solution is found or suggested

**Comment by Robbort97** [comment]
Rebal might be eligible for a tax benefit. For this he has to apply for a WBSO R&D certificate. The RVO will then decide if he is eligible. I will communicate this with Rebal and help him if necessary.

To log in to the RVO and apply he needs eHerkenning. This will cost about €40,-. 

I have communicated all of this to Rebal and will help him if he needs it.

**Comment by theblockstalk** [comment]
maybe need to check with Rebal on follow up tasks
