### ISSUE TITLE
Find additional banks

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#231]
Also check  bunq
Make an implementation suggestion with Cal.com
do a simple swot analysis
(Why do we want this, what wouldn't we want it, What can be good, what could go wrong)
if there are any financials, what are they

- [ ] bank was found if needed
- [ ]  Applied to 2 bank accounts

**Comment by kamitor** [comment]
![Screenshot from 2022-10-09 15-06-10.png](https://images.zenhubusercontent.com/62c6df43e6bcf2300a200098/c3a09572-20e6-4a48-84b9-71f52202155c)

**Comment by kamitor** [comment]
![Screenshot from 2022-10-09 15-13-42.png](https://images.zenhubusercontent.com/62c6df43e6bcf2300a200098/b939bf4b-5a38-442e-8fab-014969d42eae)

**Comment by kamitor** [comment]
[Uploading... Screenshot from 2022-10-09 15-14-17.png]

**Comment by kamitor** [comment]
![Screenshot from 2022-10-09 15-14-43.png](https://images.zenhubusercontent.com/62c6df43e6bcf2300a200098/9faedb06-09ab-4999-8e55-49f6061a92ab)

**Comment by kamitor** [comment]
BUNQ gets INIFINTE loops. 

Several failed attempts
I thought it was my internet
But it turns out its their website

**Comment by kamitor** [comment]
![Screenshot from 2022-10-09 15-35-56.png](https://images.zenhubusercontent.com/62c6df43e6bcf2300a200098/799fa59a-3124-4f43-9e2a-8eb64f4a7ca2)

**Comment by kamitor** [comment]
ASN

**Comment by kamitor** [comment]
https://wise.com/

**Comment by kamitor** [comment]
N26 SUCCESS !

**Comment by kamitor** [comment]
ASN success

**Comment by kamitor** [comment]
https://www.curve.com/signup/

**Comment by kamitor** [comment]
https://vivid.money/en-eu/compare/
