### ISSUE TITLE
 Self Sovereign Identity Workshop

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#232]
**Description:**

- What is the purpose/reason for this task?
To let contributors know better about SSI
- What current or future goal of the TF does it help achieve?
It will create an opportunity for the personal to give ideas how Tonomy ID will be implemented

**Definition of done:**

- [ ] Workshop was performed if needed

**Comment by theblockstalk** [comment]
https://www.beautiful.ai/-NDTCtR9NWU3edeZRsEx/22

**Comment by Mrak1985** [comment]
@theblockstalk please add the link for recording so I can close it

**Comment by Mrak1985** [comment]
https://www.loom.com/share/78fb9091573a41dfa907be7429fc3a37
