### ISSUE TITLE
Catch up with Patrick Burgress about a new R&D subsedy grant 

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#233]
Description:

he's working on that has a lot of available funds

What is the purpose/reason for this task?
To get funding from them
What current or future goal of the TF does it help achieve?
Aligning with those grants will let Tonomy to achieve its goals for building ecosystem of trust
Definition of done:

- [x] Research is done
- [x] Lists of grants performed and added to the grant
https://docs.google.com/spreadsheets/d/1ZScGmG5sNVsQGpcvYQq8_k55dFlfgvFWsLiZm5-tKsU/edit

**Comment by kamitor** [comment]
https://www.loom.com/share/5ed842007ccc4dc2a8df7ddc0fde507e
