### ISSUE TITLE
Create Rebal contract

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#234]
**Description:**

- What is the purpose/reason for this task?
- What current or future goal of the TF does it help achieve?

**Definition of done:**

- [x] Created
- [x] Signed by Rebal
- [ ] Scanned and located to Google drive

**Comment by Robbort97** [comment]
Contract sent to Rebal, waiting for his response.

**Comment by Robbort97** [comment]
Rebal has signed. Will let Chris sign from Tonomy side Tuesday.

**Comment by Mrak1985** [comment]
@Robbort97 can you add the link please

**Comment by Mrak1985** [comment]
https://drive.google.com/drive/u/3/folders/1lA1GM37c3DQmx8VQuvt1bUncv5bhwlSd

**Comment by theblockstalk** [comment]
still need to archive the document
may want to revisit the contract
