### ISSUE TITLE
Legal documents for Tonomy ID  Review technical aspects 

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#235]
Description:

The purpose of this task is to review the technical aspects of Tonomy ID and ensure that they are aligned with the Terms and Conditions and Privacy Notice documents. This involves reviewing the software architecture, data flows, security features, and other technical aspects of Tonomy ID, and ensuring that they comply with the legal requirements set forth in the legal documents.

The goal of this task is to ensure that Tonomy ID is technically compliant with the legal documents, and that the legal documents accurately reflect the technical aspects of the software. This will help to reduce the risk of legal issues related to Tonomy ID, such as data breaches, non-compliance with regulations, and user disputes.

To achieve this goal, we will first review the Terms and Conditions and Privacy Notice documents to identify the relevant technical requirements and restrictions. We will then conduct a technical review of Tonomy ID to ensure that it meets these requirements and restrictions.

The technical review will involve examining the software architecture, data flows, security features, and other relevant technical aspects of Tonomy ID. We will also conduct testing and simulation to identify any potential issues or vulnerabilities in the system.

Once we have completed the technical review, we will document the findings and make any necessary updates to the Terms and Conditions and Privacy Notice documents to ensure that they accurately reflect the technical aspects of Tonomy ID. We will also provide feedback and recommendations to the development team to improve the technical compliance of Tonomy ID.

Definition of Done:

- [ ] Reviewed the Terms and Conditions and Privacy Notice documents to identify the relevant technical requirements and restrictions.
- [ ] Conducted a technical review of Tonomy ID to ensure that it meets these requirements and restrictions, including examining the software architecture, data flows, security features, and other relevant technical aspects of the software.
- [ ] Conducted testing and simulation to identify any potential issues or vulnerabilities in the system.
- [ ] Documented the findings of the technical review and provided feedback and recommendations to the development team to improve the technical compliance of Tonomy ID.
- [ ] Updated the Terms and Conditions and Privacy Notice documents to accurately reflect the technical aspects of Tonomy ID.
- [ ] Presented the findings and recommendations to relevant teams and stakeholders to inform decision-making for the development and legal compliance of Tonomy ID.
- [ ] Documented the review process and findings in a central location for future reference.

**Comment by Robbort97** [comment]
Checking Jolocom, BrightID and Selfkey for their EULA and PP, see if we can copy stuff from them.

**Comment by Robbort97** [comment]
EULA Tonomy ID: https://docs.google.com/document/d/12fnL_i-dnIvloHEz0JfoA5Ydsabhg3FK_-EVAMJPyhg/edit#

**Comment by Robbort97** [comment]
Privacy Policy Tonomy ID: https://docs.google.com/document/d/1EPQoyMMfZOH37VjJfwAJ7d6Ulgf9xYAtXq9AFKJ_Oas/edit#
