### ISSUE TITLE
Give credentials to Musketeers and Ibrahim etc 

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/management#239]
Make sure the musketeers get on track and have everything they need

**Comment by kamitor** [comment]
Building a new digital ocean droplet with wordpress

This time taking the default template from the marketplace

**Comment by kamitor** [comment]
The Droplet was created however the SSL won't agree

**Comment by kamitor** [comment]
Cloudflare and Digital Ocean have problems with Certifications

**Comment by Mrak1985** [comment]
@kamitor evidence to close this task? Video or picture would be nice
