### ISSUE TITLE
Research and outline for Opensociety

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#24]
Definition of done:

- [x] Research Opensociety for grant strategies
- [ ] Create the proposal outline that we could send to them
- [x] Get feedback on the proposal outlines

**Comment by Carrie22022** [comment]
NOTE: Right now the only grants available are related to democratic practices. I think we might be able to use our idea to form a democratic practice – such as allowing blockchain technology (and Tonomy ID) to help voters safely vote from any mobile device. If we could do this, and partner with folks in Africa (I have some contacts, as I’ve spent time doing humanitarian work building power systems in Africa), we could set it up fairly quickly and start discussions. Please let me know the interest. I'd be happy to assist and/or lead this project. It would help us build use cases as well. Perhaps Mia this might be a start for our company? There are established professors here at Seattle university and possibly the University of Washington that might be interested in helping us as well.

**Comment by Mrak1985** [comment]
@Carrie22022 I think we should not close the issue until we have accomplished all definitions of done for the issue. I believe we should prepare for this grant https://www.opensocietyfoundations.org/grants/open-society-initiative-for-eastern-africa   . That we will create Tonomy ID, Wallet, Governance and DAO factory, all that will allow the African people to have transparency and opportunity to have their ID, wallet etc. Check this proposal, and you can from that create outline. Let's stick to the definition of done - we have to figure out how to apply for the open grant opportunity  https://docs.google.com/document/d/1FHFSkcdKmqsxTX4pE6Dens6YsZUU0Uq9McsmLuIuPpQ/edit

**Comment by theblockstalk** [comment]
@Carrie22022 to add description of what was done, why we stopped and what we should do next. then move back to product backlog

**Comment by Carrie22022** [comment]
This research has been completed. The draft will be a separate item.

**Comment by kamitor** [comment]
We are not developed enough to apply to this one, because it needs advanced democracies implementations?

Open another tasks for when we are ready, do what the high level grants are and only apply on those. 
(another task needed for the High level grants still listed there)..

**Comment by kamitor** [comment]
@mike closed it :)

**Comment by kamitor** [comment]
@Mrak1985 add new task for high level grants for open society and please link to this task in the past :)
