### ISSUE TITLE
Full draft proposal for Opensociety

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#25]
Definition of done:

- [ ] Create a full draft of the proposal

**Comment by YegorTDK** [comment]
I don't think a draft can be created right now, cause the website says that each call has its own requirments (sometimes a letter of inquiry or a request for the proposal is required, etc.). Currently none of the active calls fits our goals

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/1k3w87EVq8kr_QlZP_MM-H0ZJKjTgB0HSk7gFO1hofZk/edit

https://www.osiea.org/grants/#1497821895612-286716a9-a1d8

[https://app.zenhub.com/files/510762397/e67d067f-4f69-4c64-bb6e-a9b86f63a0a8/download](https://app.zenhub.com/files/510762397/e67d067f-4f69-4c64-bb6e-a9b86f63a0a8/download)

**Comment by Mrak1985** [comment]
10.5 for Mike, 10.5 for Yegor
