### ISSUE TITLE
Wordpress website homepage - draft story

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#251]
The aim of this task is to outline a detailed audience and story that will be told on the homepage

Definition of done

- [x] Document exists with a list of target audience personas and why they are interested in Tonomy Foundation
- [x] A draft story is made (and documented) with a message for the target audience. This story should answer a few questions, and aim to convince our audience to join Tonomy Foundation (as a contributor, partner, client or funder etc)
- [x] Board reviews story and gives feedback

Qs:
- what is the Tonomy Foundation?
- what is the Tonomy Foundation doing?
- why is this important for me, why should I care?
- how can I get involved? button / newsletter / how contact us?

Remember, the homepage is general, and about the Tonomy Foundation as a whole, not focused on the Tonomy ID product which will be a separate landing page. The homepage should probably mention our products.

Please think of other important questions that should be answered in the message. What would you want to see on the home page? what do you think other members of our target audience would want to see on the home page? what do we want others to see on our homepage?

Please reach out and get inspired by the rest of the team for this task.

**Comment by Mrak1985** [comment]
@NotTheRealMax Hi, can you share the link please?

**Comment by Xdsylar** [comment]
@Mrak1985  Here is the link to the draft story document which Max made

https://docs.google.com/document/d/1Ygw8WKN4WrPl6lCBkjPKSCvupM8OLRzBdREGK_68gF0/edit?usp=share_link
