### ISSUE TITLE
Wordpress website homepage - content

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#258]
The aim of this task is to generate the content that will be on the home page, based on the story

Definition of done

- [x] A single page application homepage design comprises of several sections (e.g. team, or vision).  Create and document a list of each section of the homepage, and what type of content will be in there
- [x] Create the content for each section. E.g. for Team section (if it will be on homepage), compile all the teammates, names linkedin links and photos. get images from image tools if needed

- [x]  Section 1 done

- [x]  Section 2 done

- [x]  Section 3 done

- [x]  Section 4 done

- [x] Section 5 done

- [x]  Section 6 done

- [x]  Section 7 done

Please reach out and get inspired by the rest of the team for this task.

**Comment by theblockstalk** [comment]
https://docs.google.com/document/d/1QmT3B8kYUK6put4wZ1H5nPgBji9U7KkF8LBe2Sz5cwA/edit

**Comment by Xdsylar** [comment]
UPDATE ! 

jack has made a proposal for the sections of the homepage which i will be working on  rightnow working on section 1

**Comment by Xdsylar** [comment]
UPDATE !

I have divided the  task in smaller section so that I can achieve my victory in milestones instead of one big road

**Comment by Xdsylar** [comment]
UPDATE !

I have finished the first two ( 1 & 2 ) sections of my task and will be trying to achieve 2 more today

**Comment by Xdsylar** [comment]
UPDATE ! 

Section 3 is now almost finished  i.m.o i need a little more information about 3 of the 4 core modules tonomy is creating (Tonomy DAO,Tonomy Gov and Tonomy Token) since I do not really know much about these modules

**Comment by Xdsylar** [comment]
UPDATE!

I have completed Section 7 of my Task and am slowly but surely gathering information for section 3,4 and 6

**Comment by Xdsylar** [comment]
UPDATE!

I am now finished with section 5 but i am currently blocked since section 4 is about 'who is our product for' and I dont know who is our target audience.

**Comment by Xdsylar** [comment]
UPDATE!

Chris helped me with my blocker and right now every section is done!! and READY FOR REVIEW!!! WOOOOOOOOOOOOO
