### ISSUE TITLE
Finalize and submit Opensociety proposal

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#26]
Definition of done:

- [ ] Get feedback on draft of proposal
- [ ] Proposal is finalized based on feedback
- [ ] Proposal is submitted

**Comment by Mrak1985** [comment]
Download and complete the grants application concept and submit to grants@osiea.org. Please note that the submission of the concept does not guarantee funding. The concept note will be reviewed and should it be accepted, you will be requested to submit a proposal that might be considered for funding. If you do not receive feedback within a month after submitting your concept note, please consider your bid unsuccessful.

**Comment by Mrak1985** [comment]
![image.png](https://images.zenhubusercontent.com/62c6a6e69c59cc221bd21079/706c0e47-6ea8-4469-91e7-10dd0bad143a)

**Comment by Mrak1985** [comment]
6.5 points for Mike, 6.5 for Yegor
