### ISSUE TITLE
Wordpress website homepage - similar website and other research

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#260]
The aim of this task is to be inspired by other designs and content

Definition of done:

- [x] Review Websites with a similar purpose to the Tonomy Foundation
- [x] Create a short 1 page summary (bullet points) about what we good and bad about each website's homepage, and what messages and content could be inspiring for the Tonomy Foundation homepage

Websites:

- https://oneproject.org/
- https://trustgrid.com/product/
- https://gaia-x.eu/
- https://www.crypto-commons.org/crypto-commons-association
- https://society4th.org/

**Comment by TheFakeBasS** [comment]
https://docs.google.com/document/d/18cowir-lgB8mdE0SwlZMheF64m5dCU9h/edit?usp=sharing&ouid=116843465257160402617&rtpof=true&sd=true

**Comment by theblockstalk** [comment]
https://identity.foundation/
