### ISSUE TITLE
JAMStack website - connect to Github pages

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#262]
The email this task is to connect the website to github pages

https://www.makeuseof.com/how-to-deploy-react-app-with-github-pages/

definition of done

- [x] Anybody can access the react app at a github pages domain

**Comment by Mrak1985** [comment]
@NotTheRealMax can you attach links please? So I can check how it was done?

**Comment by NotTheRealMax** [comment]
yeah sorry my bad but here ya go https://tonomy-foundation.github.io
