### ISSUE TITLE
Website meeting to discuss strategy, story and integration

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#267]
The aim of this task is for everybody working on the new homepage lines on the story and how to get to a deployed homepage. This is to ensure everybody is aligned, and working towards a single. The discussion can be inspiration for the story and content

Definition of done

- [x] Involved parties all join a meeting together
- [x] the story is discussed in detail and what kind of activities and content are on the homepage are discussed
- [ ] the meeting is documented

**Comment by NotTheRealMax** [comment]
https://www.figma.com/file/mZWQ1Lxuj4DVucsPJlQPSJ/Untitled?node-id=0%3A1
