### ISSUE TITLE
Check if the IP agreement is still needed

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#268]
We have recently received feedback that our IP agreements may not be needed based on the open source way of working we are using Finish the current IP agreement
modify that says it does not apply to the software - which is licensed from the repository
need to countersign for the non-software developers
and redo for the developers that are also working on other things

Definition of done

- [x] Deterministic current IP agreement make sense within the context of our open source software
- [x] Document is updated

**Comment by Robbort97** [comment]
Added a provision that this does not apply to the software, now needs to be signed by necessary people.

**Comment by Robbort97** [comment]
Yes, it's necessary for people that don't work on software and if they work on software and something else I add the provision that it doesn't apply to the software
