### ISSUE TITLE
Tonomy ID T&C's - full draft

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#269]
Description:

The purpose of this task is to create a full draft of the Tonomy ID Terms and Conditions (T&C's), which will govern the relationship between Tonomy Foundation and our users when using Tonomy ID, our open source identity management platform.

The goal of this task is to ensure that our users understand their rights and responsibilities when using Tonomy ID and that we are in compliance with applicable laws and regulations.

To achieve this goal, we will first research and identify the relevant laws and regulations that apply to Tonomy Foundation and our use of Tonomy ID. We will then create a comprehensive draft of the T&C's that includes all required elements under these laws and regulations, as well as any additional information that we believe is important for our users to know.

The draft T&C's will be reviewed and revised as necessary by our legal team to ensure that they are accurate, complete, and legally compliant. We will also consider feedback from users and stakeholders to ensure that the T&C's are clear and easy to understand.

Once the full draft of the T&C's is complete, we will publish them on our website and require users to agree to them when they create a Tonomy ID account. We will also ensure that the T&C's are easily accessible and prominently displayed on our website.

Definition of Done:

- [x] Researched and identified the relevant laws and regulations that apply to Tonomy Foundation and our use of Tonomy ID.
- [x] Created a comprehensive draft of the Tonomy ID Terms and Conditions that includes all required elements under these laws and regulations, as well as any additional information that we believe is important for our users to know.
- [ ] Reviewed and revised the draft T&C's as necessary with input from legal and other relevant teams to ensure their accuracy, completeness, and compliance with laws and regulations.
- [ ] Considered feedback from users and stakeholders to ensure that the T&C's are clear and easy to understand.
- [ ] Published the T&C's on our website and required users to agree to them when they create a Tonomy ID account.
- [ ] Ensured that the T&C's are easily accessible and prominently displayed on our website.
- [ ] Documented the creation and publication of the T&C's in a central location for future reference.

**Comment by theblockstalk** [comment]
this is about Tonomy ID not the website. The website does not need T&Cs

**Comment by Robbort97** [comment]
https://docs.google.com/document/d/12fnL_i-dnIvloHEz0JfoA5Ydsabhg3FK_-EVAMJPyhg/edit

**Comment by kamitor** [comment]
What is needed to be done in order to

**Comment by Mrak1985** [comment]
@Robbort97 reviewed
