### ISSUE TITLE
Tonomy ID Privacy Notice - full draft

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#270]
Description:

The purpose of this task is to create a full draft of the Tonomy ID Privacy Notice, which will inform users of how their personal data will be collected, used, and protected by Tonomy Foundation when using Tonomy ID, our open source identity management platform.

The goal of this task is to ensure that our users understand their privacy rights when using Tonomy ID and that we are in compliance with applicable privacy laws and regulations.

To achieve this goal, we will first research and identify the relevant privacy laws and regulations that apply to Tonomy Foundation and our use of personal data in Tonomy ID. We will then create a comprehensive draft of the Tonomy ID Privacy Notice that includes all required elements under these laws and regulations, as well as any additional information that we believe is important for our users to know.

The draft Privacy Notice will be reviewed and revised as necessary by our legal team to ensure that it is accurate, complete, and legally compliant. We will also consider feedback from users and stakeholders to ensure that the Privacy Notice is clear and easy to understand.

Once the full draft of the Privacy Notice is complete, we will publish it on our website and provide it to users when they create a Tonomy ID account. We will also ensure that the Privacy Notice is easily accessible and prominently displayed on our website.

Definition of Done:

- [ ] Researched and identified the relevant privacy laws and regulations that apply to Tonomy Foundation and our use of personal data in Tonomy ID.
- [ ] Created a comprehensive draft of the Tonomy ID Privacy Notice that includes all required elements under these laws and regulations, as well as any additional information that we believe is important for our users to know.
- [ ] Reviewed and revised the draft Privacy Notice as necessary with input from legal and other relevant teams to ensure its accuracy, completeness, and compliance with privacy laws and regulations.
- [ ] Considered feedback from users and stakeholders to ensure that the Privacy Notice is clear and easy to understand.
- [ ] Published the Privacy Notice on our website and provided it to users when they create a Tonomy ID account.
- [ ] Ensured that the Privacy Notice is easily accessible and prominently displayed on our website.
- [ ] Documented the creation and publication of the Privacy Notice in a central location for future reference.

**Comment by Robbort97** [comment]
https://docs.google.com/document/d/1EPQoyMMfZOH37VjJfwAJ7d6Ulgf9xYAtXq9AFKJ_Oas/edit

**Comment by Robbort97** [comment]
https://docs.google.com/document/d/1EPQoyMMfZOH37VjJfwAJ7d6Ulgf9xYAtXq9AFKJ_Oas/

**Comment by Mrak1985** [comment]
@Robbort97 I have reviewed
