### ISSUE TITLE
Social innovations security grant - create idea

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#273]
The purpose of this task is to get alignment on the proposal we will submit, and identify any partners.
https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-details/horizon-cl3-2022-ssri-01-04;callCode=null;freeTextSearchKeyword=identity;matchWholeText=true;typeCodes=1;statusCodes=31094501,31094502;programmePeriod=null;programCcm2Id=null;programDivisionCode=null;focusAreaCode=null;destination=null;mission=null;geographicalZonesCode=null;programmeDivisionProspect=null;startDateLte=null;startDateGte=null;crossCuttingPriorityCode=null;cpvCode=null;performanceOfDelivery=null;sortQuery=sortStatus;orderBy=asc;onlyTenders=false;topicListKey=callTopicSearchTableState

Definition of done

- [x] A clear proposal concept is developed, or multiple ideas are developed
- [x] somebody from the technical team reviews and verifies their validity
- [ ] A final proposal concept Is chosen and agreed on. this could have a value proposition (not required). it should propose the concept, and how it addresses the tender

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/1o6bftdw3fqo7sGEu3-h7whN1eWu7T6eBJyRZAxmtpiQ/edit

**Comment by YegorTDK** [comment]
https://drive.google.com/drive/folders/1gaCv56fS_edSGYcVbRaukmylFcud69M9
