### ISSUE TITLE
find a sales and business developer

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#279]
The name of this task is to make it known we are looking for a sales developer

Definition of done

What is the purpose/reason for this task?
To have one or two sales people

What current or future goal of the TF does it help achieve?
Is to get the right person who can boost our product selling

Definition of done:

- [x]  create post for Sales as INTERN AND VOLUNTEER
- [x] create screening tasks
- [x]  send to all candidates the screening task 
- [x]  based on their answers setup series of interviews

**Comment by Mrak1985** [comment]
https://www.notion.so/tonomy-foundation/2022-10-13-Kwadwo-AduTwum-Interview-a87a769b53694c9289bf6a9cdd1d3489  a potential candidate

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/1JB4nMtiJGvU49up1icazZiWvPFSbOBkPvTKebv1mgmw/edit

**Comment by Mrak1985** [comment]
![image.png](https://images.zenhubusercontent.com/62c6a6e69c59cc221bd21079/e5cab877-9d48-4091-80a3-75c421facd30)

Might need to be repeated. Only 2 interviews came out of it
