### ISSUE TITLE
Create post on Jack's medium

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#28]
**Definition of done:**

- [x] Post draft created with an introduction to Tonomy and Tonomy ID
- [x] Reviewed
- [x] Posted on Medium

**Comment by theblockstalk** [comment]
draft started
https://docs.google.com/document/d/1GkLXjxHupz7hXjgMhU1u9QL8zr01V_7fpYLM_xHLMBI/edit

**Comment by theblockstalk** [comment]
finished for review
https://medium.com/@theblockstalk/tonomy-foundation-building-ecosystems-of-trust-part-1-global-governance-a52f660cf0d6

**Comment by theblockstalk** [comment]
I think we need to have Linkedin and Twitter posts ready before we post on Twitter. Just we close this and then make another task to write these posts, and are published on Medium.

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/10NBsOw36EHFRFSa_SoQrcbdk-s0csn2VcKX2GpWd_bE/edit#

**Comment by Mrak1985** [comment]
@theblockstalk can you elaborate more why we need to post on Link and Twitter before Medium please?

**Comment by theblockstalk** [comment]
published
https://blog.tonomy.foundation/tonomy-foundation-building-ecosystems-of-trust-part-1-global-governance-a52f660cf0d6

**Comment by theblockstalk** [comment]
@Mrak1985 see https://tonomyfoundation.rocket.chat/channel/Marketing?msg=PCWgEADPdnnEeaWC8 for reason
