### ISSUE TITLE
Create new website and demo

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#282]
the aim of this task is to create React app showing a basic homepage with some content for Tonomy  Foundation

Definition of done

- [x] home page exists that can be demoed (can be local demo or Github pages)
- [x] home page shows some content relevant to Tonomy Foundation

**Comment by mertkama** [comment]
website sections were created.

It was deployed with the `vercel` application.

Link is here https://tonomy-website-modern-website-master.vercel.app/

For better performance, the photos were transferred to the `cloudinary` application and directed from there.

**Comment by mertkama** [comment]
I think the things we need for now are;

* Website SEO compatible content

* Suggestion to write roadmap in an application like `gitbook`

* Should WhitePaper be in `footer` or `header`

* What kind of user experience do competitors offer customers?

* Opinion advice from Jack Chris and Mike on the platforms we've built
