### ISSUE TITLE
Chefchain - meeting to formalize agreement and work together in partnership

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#283]
The aim of this task is to formalise our agreement further with Chefchain, and agree on a way that we can work in a commercially sustainable way

Definition of done:

- [ ] Agreement is made that outlines a commercially sustainable partnership where we can work for them. e.g. we work for them in prepaid credits that are paid off as soon as they are funded, or (less ideally) in equity

Follow up is going to be to create a simple legal document with the agremment

**Comment by kamitor** [comment]
Attempt this weekend

**Comment by kamitor** [comment]
... For now its in the back burner for them
