### ISSUE TITLE
Student administration and support (Sprint starting 8 Nov)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#286]
The aim of this task is to ensure any administration needs of our interns are met and that they are supported within the organisation

Definition of done:

- [x] follow muskateer, ibrahim and ahkmed updates on github and wordpress, keep them active every day. asking them what they are doing, and if there are any real blockers
- [x] talk with Aymen teacher about his involvment
- [ ] checkup with Robert and teacher that he uploaded documents

**Comment by Mrak1985** [comment]
@kamitor please add teacher's contacts so everyone can do it

**Comment by kamitor** [comment]
Jim Dunk - Musketeers - ROCMN

               - Aymen - Deltion
  Robert           - Hogeschool Windesheim
