### ISSUE TITLE
Collect everyone's salary expectations

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#288]
The aim of this task is to collect salary expectations so that we can calculate expected costs

Definition of done

- [x] all major contributor salary expectations are collected and documented, other expectations for implement are also collected (e.g. bonus', pension, freelance / employment or other)

**Comment by Mrak1985** [comment]
Created a document with bare minimum expectations https://docs.google.com/spreadsheets/d/1WtVYisOZpoF6COA8c-ZyW4KsIA6EAHGVMKEuT7tSciY/edit#gid=1806665470
