### ISSUE TITLE
Finish social media strategy

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#29]
**Definition of done:**

- [ ] Social media strategy documents are created
- [ ] Reviewed and finalized

**Comment by justaklaus** [comment]
[https://docs.google.com/presentation/d/1hE_4GmDnEB6PABW0RmqQn0nGCbeiQmvJNGtTaJNxjig/edit?usp=sharing]

Link for the marketing strategy presentation.

**Comment by justaklaus** [comment]
![Screenshot 2022-07-27 at 10.55.32.png](https://images.zenhubusercontent.com/62c6e3b8e9de48565b9abf6e/17f3f561-2690-4b36-83f2-036243db20a2)

**Comment by justaklaus** [comment]
With the workshop and Chris taking reins over it, I have shifted to creating a philosophy, or a way of creating the content that is more easy and simple than the current method. It is now done, and awaits feedback. All updates are seen on the link in this task
