### ISSUE TITLE
Review IP agreement and if it makes sense

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#291]
The aim of this task is to re-assess if the IP agreement makes sense

Definition of done

- [x] understand why we shouldn't shouldn't have an IP agreement for open source software. document reasons for and against
- [ ] if we should have it, then finish executing and archiving all IP agreements

**Comment by theblockstalk** [comment]
see notes here
https://www.notion.so/tonomy-foundation/2022-10-12-weekly-strategy-3e6cfb07c9e247c8b852de81c639fc39#33e97f593c54456b9bb51886f5fd3e31

**Comment by Robbort97** [comment]
The Apache License Version 2.0 provides similar freedom as the 3 clause bsd; however, it provides more specific information about the associated legal terms. https://www.apache.org/licenses/LICENSE-2.0

**Comment by Robbort97** [comment]
This is the 3 clause bsd: https://opensource.org/licenses/BSD-3-Clause

**Comment by Robbort97** [comment]
I think an IP agreement still makes sense to have everyone that doesn't work on the software and use an open source license for everyone that does. And the people that work on the software can still sign it for everything they do that isnt related to the software.

**Comment by Robbort97** [comment]
We could also use GPLv3: https://www.gnu.org/licenses/gpl-3.0.html I'm going to compare it to apache 2.0

**Comment by Robbort97** [comment]
Apache 2.0 seems to be the better choice: https://docs.google.com/document/d/13DJaV4OL96Zc_YMTH51RQE7oAzFkB7mXwy5sGORBr-4/edit

I have also included in the document how to implement an open source license.
