### ISSUE TITLE
review Rebal contract clauses

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#292]
The aim of this task is to update rebal's contract, based on feedback from @kamitor 

Definition of done

- [x] new contract is proposed and reviewed by Rebal + other board member (based on the changing saalries and fines)
- [ ] contract is agreed on and (if agreed) executed on both sides and archived

**Comment by Robbort97** [comment]
https://docs.google.com/document/d/1dwGOfj5z0PCHOIC8S8oaM1kBA7u0pV54OGaGFwYX2DQ/edit

**Comment by Mrak1985** [comment]
@Robbort97 I've reviewed, changed from 12 months to 10 as we started payments from September
