### ISSUE TITLE
Hook up our linkedin to Rocket chat post by Zappier

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#293]
Description:

https://zapier.com/apps/rocketchat/integrations/twitter

Definition of done:

- [ ]  Hook up is done which posts to a new Rocket Chat channel every time we make a LN post

**Comment by Xdsylar** [comment]
Zappier does not have any zaps/links to link LinkedIn with Rocketchat. I found that out when I was trying to link them with Zappier, this is the image that I get: 

![Zappier linkedIn .png](https://images.zenhubusercontent.com/63232ebaf7858659f273f64d/dc4848da-6f8e-45ae-85cf-9365f0e83c27)
