### ISSUE TITLE
Fill out risk assessment

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#30]
**Definition of done:**

- [x] fill out (not Mikhail) for Tonomy ID and Customer is us (Tonomy)  https://docs.google.com/spreadsheets/d/1Z4rZt6NjxO49u8G4Qs_ygqg83buRZMvcq203ZTyQyxA/edit#gid=617037669
- [x] mark questions that think not so important
- [x] 1 person review

**Comment by Mrak1985** [comment]
Dear all, review 1 or 2 of you, mark questions which can be permanently left over and add your opinion for each Risk

**Comment by theblockstalk** [comment]
I have fully reviewed this now!
