### ISSUE TITLE
Create discord server

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/management#302]
Including Bots

- [x] Ask musketeers to join and ask musketeers to tell why discord 
- [x] Create server and make roles
- [ ] Create plan about discord server and explination
- [ ]  Setup Alliances with other discord servers
- [x]  Add more chats for regular users
- [ ]  Add flavour roles for users (think of Developer, SSI enthousiast, etc)
- [x] Create join buttons on the website 
- [x] Add to twitter etc.

**Comment by Mrak1985** [comment]
Please mark what is done and then close

**Comment by kamitor** [comment]
15 - 6

**Comment by kamitor** [comment]
15 aymen - 6 chris
