### ISSUE TITLE
Discord Community Management - Making the discord more fun and big

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/management#308]
- Monitor Hours spend building the discord flows
- At the end of the sprint we show output
- We decide how much points this was worth then

**Comment by Mrak1985** [comment]
Points to be allocated at the end of the sprint

**Comment by kamitor** [comment]
Aymen - Made sure the Rule Configuration system worked
Aymen - Is researching a Telegram to Discord Bridge

**Comment by kamitor** [comment]
Aymen is going to load a contributor section

**Comment by kamitor** [comment]
Chris lays out a bit of a plan for discord
