### ISSUE TITLE
Tonomy Trademark application submition

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#322]
**Description:**

We need to submit trademark for Tonomy to protect it 

https://docs.google.com/document/d/1jyA4WcZCY34N4MkNQHGMRXhvQiU7D8Hg2mcPHDDYeXU/edit?usp=sharing

- What is the purpose/reason for this task?
We need to submit trademark for Tonomy to protect it 

- What current or future goal of the TF does it help achieve?
Prevent legal suits towards Tonomy

**Definition of done:**

- [x] To do a research how to do it and how much it cost (presentation or document)
- [x] proposal what is to be on the trademark during board meeting
- [ ] create follow-up tasks

**Comment by Robbort97** [comment]
Presentation on what we possibly need to do: https://docs.google.com/presentation/d/12FBUDIYbyrxA-aa6YPCgHTBlCVs-MouSy__ZWRkPrt8/edit#slide=id.g19450506172_0_29

Needs followup tasks
