### ISSUE TITLE
Research EOS NETwork Foundation grant for recovery solution

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#334]
**Description:**
Apply to EOS Network Foundation again with recovery solution for EOS blockchain

- What is the purpose/reason for this task?
To get potential funding
- What current or future goal of the TF does it help achieve?
Get money for operations

**Definition of done:**

- [x] research is done with the outline how to apply

**Comment by theblockstalk** [comment]
https://docs.google.com/document/d/1mje9-qOpbY3807H-sZwCvBtv1iMyleArROmjs2gzZno
