### ISSUE TITLE
Draft version of grant to EOS Network Foundation recovery solution for EOS blockchain

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#335]
**Description:**
- What is the purpose/reason for this task?
To apply for the ENF Grant
- What current or future goal of the TF does it help achieve?
Get funding for Tonomy operations

Definitions of Done: 

- [x]  The proposal is clearly defined in a document, including all the links to those documents (the original proposal, where to find it and the output) ready for review here in the TAIGA.
- [x]  Reach out to ONE person Review by either Mike  / Jack  / Yegor> Set the task to review
- [ ]  Send out as draft to ENF community

This does NOT include  

Filing the proposal, Reviewing the proposal

**Comment by theblockstalk** [comment]
https://github.com/eosnetworkfoundation/grant-framework#grant-process-for-new-proposals

**Comment by theblockstalk** [comment]
https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/acceptance-recommendations.md

**Comment by theblockstalk** [comment]
https://docs.google.com/document/d/1tSEbmbe848AQ_iwDHfuU1uvTwscHPdoJQ5MqsCahDaY

**Comment by kamitor** [comment]
Maybe new task to send out ? ask for update Jack on Task
