### ISSUE TITLE
Grant for account recovery Finalize ENF proposal and submit

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#336]
**Description:**
After reviewing draft version, final version is to be submitted 
Definition of done:

 Finalize proposal

- [x] Submit to ENF :
- [x]  Github pull request to ENF

**Comment by theblockstalk** [comment]
https://docs.google.com/document/d/1tSEbmbe848AQ_iwDHfuU1uvTwscHPdoJQ5MqsCahDaY/edit

**Comment by theblockstalk** [comment]
submitted
https://github.com/eosnetworkfoundation/grant-framework/pull/181
