### ISSUE TITLE
Create a map with Tonomy infrastructure

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#337]
**Description:**
Create a map with Tonomy infrastructure with logins and passwords: for instance access to digital ocean, access to Accounting software, access to google drive main account, to discord, etc. 

- What is the purpose/reason for this task?
Create one file and share access among managers to prevent losing control in case of one manager accidentally wouldn't be able to communicate (wars, medical conditions, etc)

- What current or future goal of the TF does it help achieve?

**Definition of done:**

- [x] map is created
- [x] reviewed
- [x] Distributed to managers or email with delay is created to distribute such information

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/1Qpa4Er53iWsarH8Qw_j-z1U0oc_zzt9-bq3omrZOtsA/edit @theblockstalk update using this

**Comment by theblockstalk** [comment]
https://docs.google.com/spreadsheets/d/1kV-IccnG3LJHXQuBXqbU1N1m21nafHdfVS8sd93oXok/edit#gid=0

**Comment by theblockstalk** [comment]
please delete your document @Mrak1985

**Comment by Mrak1985** [comment]
@kamitor please review as well where access
