### ISSUE TITLE
Apply and get an ISO 29001 certificate

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#340]
**Description:**
https://www.iso.org/isoiec-27001-information-security.html

- What is the purpose/reason for this task?
To certified
- What current or future goal of the TF does it help achieve?
this could give clients more trust in our software

**Definition of done:**

- [x] research how to apply
- [x] gather necessary information
- [ ] aplly if necessary

**Comment by YegorTDK** [comment]
https://drive.google.com/drive/folders/14O0ZJhEBDxW5njyuxVbcwVRKN8p3cSb4

**Comment by YegorTDK** [comment]
https://www.dekra.com/en/iso-27001/#elementnull01

A link on how to apply for the certificate found by Robert.

**Comment by Mrak1985** [comment]
@YegorTDK do we need to apply?
