### ISSUE TITLE
How can we get democracy back to the city of Amsterdam - radio show

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#345]
**Description:**
14 th of December radio talk show where the Dutch speaking person can tell about Tonomy and plans

- What is the purpose/reason for this task?
- What current or future goal of the TF does it help achieve?

**Definition of done:**

- [x] send Chris's details

**Comment by mertkama** [comment]
I don't know if radio is still used in the Netherlands, but it may be more logical to create a podcast series on spotify, or there may be other podcast applications.
