### ISSUE TITLE
Create FINAL official document for loans

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#349]
Description:

What is the purpose/reason for this task?
To state clearly what is expected to be loaned and on what condition
What current or future goal of the TF does it help achieve?
Definition of done:

Final document is in the Tonomy folder

- [ ] Follow up after this task

legal check

**Comment by Robbort97** [comment]
https://docs.google.com/document/d/1cp7cpYL2fulfAm5WXAS-QseqINRuj7dYuOxp-V81u0Q/edit

**Comment by Robbort97** [comment]
@theblockstalk I replied to your comment in the document, can you look at it and say what you think
