### ISSUE TITLE
Get VAT number

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#350]
Definition of done

- [x]  do research
- [x] questionnaire filled
- [x]  apply for the VAT
- [x]  foundation has a VAT Number

**Comment by Robbort97** [comment]
Got a form of the tax offices to receive a questionnaire to see which taxes we have to pay. Very handy to do and necessary to receive VAT number.

Will take 4 weeks to receive it so will do this tomorrow.

**Comment by Robbort97** [comment]
Still waiting for the form from the tax offices, should arrive in a few days

**Comment by Mrak1985** [comment]
@Robbort97 any update?

**Comment by Robbort97** [comment]
No, I didn't get the form, maybe @kamitor got it? I will just call the tax office tomorrow.

**Comment by Mrak1985** [comment]
@Robbort97 may be we need to send one more form and call them?

**Comment by kamitor** [comment]
Omzetbelastingnummer
863999402B01
Btw-identificatienummer
VAT number
NL863999402B01
