### ISSUE TITLE
Discord Community Management - Making the discord more fun and big

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#351]
Monitor Hours spend building the discord flows
At the end of the sprint we show output
We decide how much points this was worth then

**Comment by TheFakeBasS** [comment]
Update added the idleRPG bot

**Comment by TheFakeBasS** [comment]
Update added a discord link to the wordpress page so more people can join our discord

**Comment by Xdsylar** [comment]
UPDATE!

we have added a few bots in our own discord and are ready to invite them to the tonomy discord

**Comment by Xdsylar** [comment]
UPDATE!

we have made a suggestion for the discord link on the tonomy linkedin profile since it is smashed together with our motto now

**Comment by TheFakeBasS** [comment]
https://docs.google.com/document/d/1U76Wsvhk0J--yYIv8IoSgXMYeXLRPUjO3l6RM0vgFTE/edit?usp=share_link
