### ISSUE TITLE
Wordpress website footer

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#355]
Definition of done

- [x] footer has links to socials
- [x] footer has link to Linkedin jobs
- [x] copyright notice

be inspired by https://tonomy-website-modern-website-master.vercel.app/

**Comment by Xdsylar** [comment]
https://tonomy.foundation/wp-admin/post.php?post=4643&action=edit

**Comment by Xdsylar** [comment]
UPDATE !

I have updated the footer colours to the tonomy collors, Bas noticed and I instantly changed it
