### ISSUE TITLE
Wordpress website homepage - graphical content

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#361]
Definition of done:

- [ ] create visual graphics for the content on the homepage

Hints:

- create / modify existing yourself in Figma
- create in canva
- find sources on https://www.freepik.com or others

**Comment by TheFakeBasS** [comment]
https://docs.google.com/document/d/1PpPASzhJY3tcRK5Ld2jpLtKDpFWMPf2Dsrl7Baqv6c0/edit?usp=share_link
