### ISSUE TITLE
Research and outline for Opensociety

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#364]
https://www.opensocietyfoundations.org/grants

Definition of done:

- [x]  Research Opensociety for grant strategies
- [ ]  Create the proposal outline that we could send to them
- [x]  Get feedback on the proposal outlines

**Comment by YegorTDK** [comment]
Currently there are 5 grant/fellowship programs available:

1. Leadership in Government Fellowship (https://www.opensocietyfoundations.org/grants/leadership-in-government-fellowship)
The Open Society Foundations’ Leadership in Government Fellowships Program was founded in 2016 to support former senior-level government staff in the United States who have recently left public service and have played a significant role in advancing social change from within government in the United States at the city, county, tribal, state, and federal levels. We are interested in public sector leaders that have a deep interest in using this fellowship opportunity to reflect on their time in government and to undertake a project that advances policy ideas and inserts their unique perspectives about making change from within government into the public dialogue.

2. Soros Equality Fellowship (https://www.opensocietyfoundations.org/grants/soros-equality-fellowship)
The Soros Equality Fellowship seeks to support individual leaders influencing the racial justice field. We understand the unique role an individual can play in rejecting old paradigms and presenting an affirmative vision for an inclusive multiracial democracy. We invite applicants to be bold, innovative, and audacious in their submissions. The aim of the Fellowship is to be flexible and open—a space to incubate new ideas, promote risk-taking, and develop different ways of thinking that challenge and expand our existing assumptions. A successful project should identify a challenge and propose a critical intervention that will meaningfully address the systems that reinforce inequities and discrimination in the United States.

3. Soros Justice Fellowships (https://www.opensocietyfoundations.org/grants/soros-justice-fellowships)
The Soros Justice Fellowships support outstanding individuals—including lawyers, advocates, grassroots organizers, writers, print and broadcast journalists, artists, filmmakers, and other individuals with distinctive voices—to undertake full-time projects that engage and inform, spur debate and conversation, change policy or practice, and catalyze change around the U.S. criminal legal system at the local, state, and national levels. Fellowships can be either 12 or 18 months in duration, may be undertaken with the support of a host organization, and should begin in the fall of 2023.

4. Latin America Program (https://www.opensocietyfoundations.org/grants/latin-america-program-grant)
The Latin America Program addresses rights and governance issues in Latin America and the Caribbean through grant making, network building, and collaboration with partners. We focus on supporting Latin American and Caribbean efforts to defend democracy and increase governmental transparency, protect minority rights, reduce homicides, and reform drug policy.

5. Open Society Initiative for Eastern Africa (https://www.opensocietyfoundations.org/grants/open-society-initiative-for-eastern-africa)
OSIEA plays an active role in encouraging open, informed dialogue on issues of importance in Eastern Africa. Through a combination of grant making, advocacy and convening power, OSIEA is able to support and amplify the voices of pro-democracy organizations and individuals in the region and to strengthen their capacity to hold their governments accountable. This includes efforts to defend and support rights activists and pro-democracy advocates who come under attack for their work.

Not sure if any of them fits our goal

**Comment by Mrak1985** [comment]
I think we can research for those two - what are the requirements?
Latin America Program (https://www.opensocietyfoundations.org/grants/latin-america-program-grant)
The Latin America Program addresses rights and governance issues in Latin America and the Caribbean through grant making, network building, and collaboration with partners. We focus on supporting Latin American and Caribbean efforts to defend democracy and increase governmental transparency, protect minority rights, reduce homicides, and reform drug policy.

Open Society Initiative for Eastern Africa (https://www.opensocietyfoundations.org/grants/open-society-initiative-for-eastern-africa)
OSIEA plays an active role in encouraging open, informed dialogue on issues of importance in Eastern Africa. Through a combination of grant making, advocacy and convening power, OSIEA is able to support and amplify the voices of pro-democracy organizations and individuals in the region and to strengthen their capacity to hold their governments accountable. This includes efforts to defend and support rights activists and pro-democracy advocates who come under attack for their work.
