### ISSUE TITLE
Create personality map of contributors

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#37]
**Description:**

Information on the map:

1. all contributors and their personalities, as well as what personalities we are missing
2. for all the executives (Mike, Carrie, Chris, Mia and Jack) show
strength and weaknesses
personality type
3. things they want to do (to be filled in in a meeting together)
also add Suneet, Rebal and Stefan

primary responsibilities
**Definition of done:**

- [x] Map created
- [x] Discussed and finished in meeting

**Comment by Mrak1985** [comment]
![image.png](https://images.zenhubusercontent.com/62c6a6e69c59cc221bd21079/b5b4bd43-5d02-4ae5-a68a-34b62f062326)

**Comment by Mrak1985** [comment]
it is in our CRM
