### ISSUE TITLE
Sign and archive the loan agreement, and pay any loans due to the bank account

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#371]
**Description:**

- What is the purpose/reason for this task?
To make loans official
- What current or future goal of the TF does it help achieve?
Have a procedure for loans

**Definition of done:**

- [x] loans are signed and located on the google drive
- [x] Jack has signed
- [ ] Chris if needed

**Comment by Mrak1985** [comment]
@Robbort97 any update?

**Comment by Robbort97** [comment]
@kamitor and @theblockstalk still need to fill in how much they want to loan to Tonomy in the contract

**Comment by theblockstalk** [comment]
I think this is done. I just did mine. Chris is fully paid back so unnecessary now.
