### ISSUE TITLE
Switch all subscriptions like Google to use the new bank account

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#372]
**Description:**

- What is the purpose/reason for this task?
to let automation safe time for payments
- What current or future goal of the TF does it help achieve?
Have official payments to show our expenses

Check expense report to understand what we are paying and freelancer account

**Definition of done:**

- [ ] Notion is moved
- [ ] Openocean is moved
- [ ] Google is moved
- [ ] Fresshbook
- [ ]
- [ ]
- [ ]
- [ ]
- [ ]
- [ ]- [ ]

**Comment by theblockstalk** [comment]
TODO

- [x] Rocketchat
- [x] notion
- [x] google
- [x] digital ocean
- [x] freshbook
- [x] aws
- [x] freelancer
- [x] medium
- [x] figma
