### ISSUE TITLE
Migrate wordpress to a managed service, instead of us managing the server

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#373]
**Description:**

- What is the purpose/reason for this task?
Have more efficient website
- What current or future goal of the TF does it help achieve?

**Definition of done:**

- [ ] full backup
- [ ] create a new service in digital ocean
- [ ] import the backup
- [ ] check it is all the same and delete the old server - IMPORTANT TO DELETE
- [ ] update DNS to point to the new service

**Comment by kamitor** [comment]
cancelled;  no longer needed
