### ISSUE TITLE
Sign Rebal contract

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#374]
What is the purpose/reason for this task?
What current or future goal of the TF does it help achieve?
Definition of done: 

- [ ]  Signed by Rebal
- [ ] Signed by Tonomy
- [ ]  Scanned and located to Google drive

**Comment by Robbort97** [comment]
Chris didn't agree with everything in the agreement. Might ask Drew if I can copy his.

**Comment by Mrak1985** [comment]
@robbort97 you are the focal point of legal work. If Chris' comments make sense,. let's redo it. But Chris must do it earlier as well - we can't wait on him and if Rebal is decent guys and so far has signed first contact, what is the risk signing a new one?

**Comment by Robbort97** [comment]
@Mrak1985 yes Chris' comments make sense. Legal work is partially ideological as well so if Chris' has a certain goal in mind (make contracts as simple as possible) I will do that. Contract looks good now but still want to compare it to the one Drew made.

**Comment by Robbort97** [comment]
https://docs.google.com/document/d/1dwGOfj5z0PCHOIC8S8oaM1kBA7u0pV54OGaGFwYX2DQ/edit

**Comment by kamitor** [comment]
is this not done yet?

**Comment by theblockstalk** [comment]
this should be closed IMO
