### ISSUE TITLE
Calculate costs for Tonomy name trademark in Europe and north America

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#390]
**Description:**
Calculate costs for Tonomy name trademark in europe and north america

- What is the purpose/reason for this task?
To know how much it would cost
- What current or future goal of the TF does it help achieve?
Have protected name and brand

**Definition of done:**

- [ ] research how and where to calculate it
- [ ] calculations are made and written  on Google drive

**Comment by Robbort97** [comment]
Added the information to the presentation: https://docs.google.com/presentation/d/12FBUDIYbyrxA-aa6YPCgHTBlCVs-MouSy__ZWRkPrt8/edit#slide=id.g19450506172_0_11
