### ISSUE TITLE
Research Trademark's classes

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#391]
**Description:**
To do research how to apply for these trademarks

- What is the purpose/reason for this task?
To know the way to apply for trademark
- What current or future goal of the TF does it help achieve?

**Definition of done:**

- [ ] Research is done 
- [ ] research is documented to repeat this process in the future

**Comment by Robbort97** [comment]
https://docs.google.com/document/d/1LAgMJvbG0f6RGc8F_iLA-dizsO4lmePpLIi33KDkAtE/edit
