### ISSUE TITLE
Get consultation from a lawyer about trademark

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#392]
**Description:**
Get consultation from a lawyer about trademark

- What is the purpose/reason for this task?
To make sure we would do it alright
- What current or future goal of the TF does it help achieve?
To have a protected trademark for Tonomy

**Definition of done:**

- [x] consultation was taken and bullet points were written

**Comment by Robbort97** [comment]
Applying for a trademark is more difficult than I first thought. I thought we could apply for a trademark in different parts of the world through WIPO, but now I see that is not the case. The EU, UK, US and Canada each have their own platform.

**Comment by Robbort97** [comment]
I couldn't find a lawyer that is both specialized in trademark law and gives free consultations. I have send an e-mail to a law firm that is specialized to see if they can give us consultation and how much that would cost.

**Comment by Robbort97** [comment]
Sent Chris a message since he knows a couple of lawyers

**Comment by Mrak1985** [comment]
@kamitor

**Comment by kamitor** [comment]
MPL, GPL, AGPL

**Comment by kamitor** [comment]
register a trademark for it and then create a brand usage policy

**Comment by kamitor** [comment]
> as a general rule of thumb: SaaS: AGPL; end-user program: GPL; library: LGPL or MPL depending on how strict you want your copyleft to be 

This statement is providing guidance on which open source license to choose for different types of software projects, based on the desired level of "copyleft" restrictions. Copyleft is a term used in the open source community to describe the requirement that any modifications or improvements made to the code must also be released under the same open source license.

The guidance suggests that for Software as a Service (SaaS) applications, the Affero General Public License (AGPL) is a good choice. The AGPL is similar to the popular GNU General Public License (GPL), but includes specific provisions to ensure that any changes made to the code for use in a web-based service are also made available under the same license.

For end-user programs, the guidance suggests using the GPL. This license is designed for programs that are distributed to end-users in binary form and ensures that any changes to the code are also released under the GPL.

For libraries, the guidance suggests using either the Lesser GPL (LGPL) or the Mozilla Public License (MPL), depending on the level of copyleft restrictions desired. The LGPL is a more permissive version of the GPL that allows for the library to be used in proprietary software, while still requiring any modifications to the library itself to be released under the LGPL. The MPL is also a permissive license that allows for the library to be used in proprietary software, but with more explicit and flexible conditions for copyleft.

**Comment by kamitor** [comment]
https://www.wipo.int/portal/en/index.html

**Comment by Mrak1985** [comment]
@kamitor put more elaborate evidence, not 1 sentence which does not make any sense

**Comment by Mrak1985** [comment]
32 for you, 8 for Chris
