### ISSUE TITLE
Get Telos community feedback for Telos ID

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#4]
Done:

- [x] Create feedback form and integrate with slides
- [x] Send out slides to community with feedback form on several Telegram and Discord channels, and Twitter maybe?
- [x] Update status in CRM
- [x] add links to the google drive here in TAIGA

**Comment by theblockstalk** [comment]
slides: https://www.beautiful.ai/-N506PrF7qC_ZLhgRX8J/1

survey: https://drive.google.com/drive/folders/1ip7NADQAWPGAgzDnqqx6JUpzeejqSSue

**Comment by theblockstalk** [comment]
ive sent on relevant telegram channels

**Comment by theblockstalk** [comment]
I also ended up sharing our workshop in Telegram . hope this is alright... https://t.me/HelloTelos/568950

**Comment by Mrak1985** [comment]
@Carrie22022 @theblockstalk what is the status for this task? Please update all tasks accordingly to their status

**Comment by theblockstalk** [comment]
it's done. only one external feedback. we could try pump it out more and get more feedback. did not get it on twitter but by the DOD it's done

**Comment by kamitor** [comment]
Followup tasks for : >> Pump out a bit more? 
Add a video for the wireframe? 
Update the Survey to adjust where we are now?? 

Just walking to the wireframe and the Prototype.

**Comment by kamitor** [comment]
Carrie; Maybe we need review warning system?
