### ISSUE TITLE
Finalize ENF proposal and submit

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#40]
**Definition of done:**

- [x] Finalize proposal
 Submit to ENF :
- [x] Github pull request to ENF

**Comment by theblockstalk** [comment]
proposal finalized. will wait till we submit to Pomelo before submitting

https://github.com/Tonomy-Foundation/EOS-network-foundation-grant-framework/blob/ssi-toolkit/applications/ssi-toolkit-verifiable-credentials.md

**Comment by Mrak1985** [comment]
@theblockstalk  how it is going with this task?

**Comment by theblockstalk** [comment]
I plan to submit on Monday the 1st August

**Comment by theblockstalk** [comment]
submitted https://github.com/eosnetworkfoundation/grant-framework/pull/57

@Mrak1985 you and I need to sign a contributors agreement before it is considered

**Comment by theblockstalk** [comment]
```
Thank you for your application to the ENF Grant Framework.

We recieved your Verifiable Credentials for the EOSIO application by the Tonomy Foundation team, submitted from the theblockstalk Github account.

We are working through our internal processes which includes translating the application followed by a series of meetings. Thus it may take several weeks to get back to you.

You may notice comments and feedback on your application in Github as it is being reviewed. Please respond to those comments and reviews as addressing each point will be required before the Application is given final approval.

The process is still very new and we hope to improve the speed of processing moving forward.

Thank you for your patience and understanding.
```
@Mrak1985

**Comment by kamitor** [comment]
Followup will be in Github trough Jack Tanner, They will be adding comments. 
Maybe they will ask for a call. 

Task imput??
