### ISSUE TITLE
implement SEO of the homepage

### ISSUE THREAD

**Issue by aymenae** [Tonomy-Foundation/management#402]
**Description:** Max has research on the SEO. apply them to the website.

resource: task #259

**Definition of done:**

- [x] Applied them to the website

**Comment by aymenae** [comment]
Check task #259 for research? @NotTheRealMax

**Comment by NotTheRealMax** [comment]
https://docs.google.com/document/d/1X66JyJUb9EhfjIowzOo0vo8p7LQR3-Xuc3kmgjwrKks/edit 
link to research
