### ISSUE TITLE
Create content for website

### ISSUE THREAD

**Issue by aymenae** [Tonomy-Foundation/management#403]
**Description:** The site has no content to sell Tonomy's family of SAAS products. Create them!

**Definition of done:**

- [x] Go over the current content
- [x] Decide what content you want to add (eg "autonomy", "privacy" and then Tonomy ID etc.)
- [x] Create the content (multiple tasks? edit if needed)
- [x] Send it in the #website chat and let the Musketeers/Aymen know it's finished

**Comment by TheFakeBasS** [comment]
Link to the content: https://docs.google.com/document/d/1PpPASzhJY3tcRK5Ld2jpLtKDpFWMPf2Dsrl7Baqv6c0/edit?usp=share_link

**Comment by Mrak1985** [comment]
10 Mike, 11 Chris
