### ISSUE TITLE
Fix discord rights based on Chris' guide

### ISSUE THREAD

**Issue by aymenae** [Tonomy-Foundation/management#405]
**Description:** The discord is a mess right now. It has to be cleaned up & documented so it's stable for the future.

**Make sure everything is done by Server roles & not user roles**

**Definition of done:**

- [ ] Redo roles as you see fit, so the appropriate rights are to the appropriate member
- [ ] go over the sections & align them with the new roles
- [ ] Create a private section for specific chats (finance, recruitment etc)
- [ ] Create a guide on how to use Dyno to update roles

**Comment by kamitor** [comment]
https://drive.google.com/file/d/1ubor8zGR_AsSNFs1tz6ovjaUpZTRzcxE/view?usp=sharing

**Comment by kamitor** [comment]
Current Situation

**Comment by kamitor** [comment]
Allign with Musketeers, Aymen and Mike
