### ISSUE TITLE
Redo discord chats

### ISSUE THREAD

**Issue by aymenae** [Tonomy-Foundation/management#407]
- [x] Go over all the chats and give them a reason. if there is none, put them in the archive.
- [x] Add a description to all chats that are left over.
- [x] Check chats, and see if they fit with the section they are in. if not, move them.

**Comment by NotTheRealMax** [comment]
These are some chats that I was wondering on if we still want to keep / use them since they are barely used or just no use for them.
![afbeelding.png](https://images.zenhubusercontent.com/63232df0b43026151bb6f094/b1a346bc-ab86-4d52-bea3-30dbfc2967b4)
