### ISSUE TITLE
Update logo design

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#41]
**Description:**

Design iterations, team voting, and workshop for final discussion

**Definition of done:**

- [ ] final design is chosen

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/1wOrItXhDuGOiLeBkK_ofJFH6Ig_mRKQa/edit

**Comment by theblockstalk** [comment]
@harpreet4singh 

> I have checked the doc along with voting parameters. I also went through everyone's opinion about the logo and respective rating. Here are my thoughts:

- I feel current logo is too complicated/complex
- It resonates more with electrical/semiconductor industry domain
- The internal wires are not visible when viewing on bigger devices (a normal desktop has a width of 1440 and it looks cluttered | Screenshot attached)
- We definitely need to create a brand book for proper usage over different background shades
- Color is not reflecting about the emotion associated with the overall brand personality (See reference link: https://blog.depositphotos.com/10-tips-on-how-to-choose-a-color-for-your-logo.html#:~:text=If you want your logo,red is definitely your color)

What can be done? I can give it a shot once we are done with the current design task and try some very basic variations to seek team's internal feedback.
