### ISSUE TITLE
Linkedin: add yourself to the Tonomy Foundation

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/management#411]
Prerequisite: 
- You have a linkedin Account:

- [ ] Add Tonomy Foundation as your current occupation
- [ ] Make sure you appear as employee on the LinkedIn page

Prerequisite: 
- You have a tonomy email (route : > [ Cloudflare email routing : ])

- [ ] Go to your profile:
- [ ] Add your Tonomy Email
- [ ] Verify your email
- [ ] Go to this link: https://www.linkedin.com/company/tonomy-foundation/mycompany/
- [ ] Verify that you are able to edit the LinkedIn page (AKA you are a manager of the page)

Add your name here if you did it:
- [x] Aymen
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by aymenae** [comment]
![image.png](https://images.zenhubusercontent.com/630cc6a911f77d6346e78bfc/9238ed1b-bd10-432c-aa13-f6fdde25e060)
