### ISSUE TITLE
Full draft of Pomelo grant proposal

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#42]
https://pomelo.io/grants/

**Definition of done:**

- [x] Create full draft of Pomelo grant

**Comment by Carrie22022** [comment]
Research and preparation document 
https://docs.google.com/document/d/1NQo__v2WpRIjdunAYaItiVAwusWKUaiGbW_egjkEGvw/edit#

**Comment by kamitor** [comment]
new tasks needed for the donation to EOS from this grant @Mrak1985 
@theblockstalk

**Comment by kamitor** [comment]
@theblockstalk first is to finish a prototype of the social recovery; Highest prio
2nd promote this more > both on twitter and telegram
as well as discord
<>> needs marketing included 
Use jack's twitter
Maybe medium article
@theblockstalk  signed up to pitch community 
@kamitor  wants to to join>>>>>>
Needs to be a video of the pitch deck

Each of us needs to 5 euro etc 
@kamitor will cover for stefan and rebal, Aymen
@Carrie22022 look at the finance channel . top side
