### ISSUE TITLE
Research W3F grants

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#421]
Description:
https://github.com/w3f/Grants-Program

What is the purpose/reason for this task?
To get funding from Github 
What current or future goal of the TF does it help achieve?
Aligning with those grants will let Tonomy to achieve its goals for building ecosystem of trust

Definition of done:

 Research is done
 

- [x] Lists of grants performed and added to the grant list 

https://docs.google.com/spreadsheets/d/1ZScGmG5sNVsQGpcvYQq8_k55dFlfgvFWsLiZm5-tKsU/edit

**Comment by YegorTDK** [comment]
On the website they say that they mostly work with the projects related to Polkadot and Kusama. However, they also claim to be interested in supporting other projects in the ecosystem. 

A link added to the list of grants (Web3 Foundation Grant)
