### ISSUE TITLE
create guide discord rights

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#426]
Description: The discord is a mess right now. It has to be cleaned up & documented so it's stable for the future.

Make sure everything is done by Server roles & not user roles

Definition of done:

- [x]  Redo roles as you see fit, so the appropriate rights are to the appropriate member
- [x]  go over the sections & align them with the new roles
- [x]  Map out current status
- [x]  Create future Flows

**Comment by Mrak1985** [comment]
https://drive.google.com/file/d/1ubor8zGR_AsSNFs1tz6ovjaUpZTRzcxE/view?usp=sharing

**Comment by kamitor** [comment]
https://drive.google.com/file/d/1ubor8zGR_AsSNFs1tz6ovjaUpZTRzcxE/view?usp=sharing
