### ISSUE TITLE
For new comers to read and review doctoral dissertation 

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#438]
**Description:**
For new comers to read and review doctoral dissertation 
https://drive.google.com/file/d/1W7vyusnPzBZuaxmqFNJh2bzophHihG73/view?usp=drivesdk e

except developers - for them our workshops to be enough. Especially important for marketing people

- What is the purpose/reason for this task?
To understand better marketing opportunity
- What current or future goal of the TF does it help achieve?
Become more efficient as a Tonomy member

**Definition of done:**

- [ ] Mike
- [ ] Caihao
- [ ] Yegor
- [x] Milica
- [x] Daria
- [x] Spandana

**Comment by deadex-ng** [comment]
@Mrak1985 - I've been making some notes [here](https://github.com/deadex-ng/notes). I'll be updating them.
