### ISSUE TITLE
Create a document summarizing our foundation commercial strategy

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#44]
**Description:**

Contents:

1. Commercially Sustainable in its different phases. See the summary of our discussions here:     
https://docs.google.com/presentation/d/1Bddo24e8f0pfY8lwbRr0IdvIZXS0bBUL84Bpa66W7SA/edit#slide=id.g133747ea34e_1_15
2. Technology strategy
3. Legal and culture

This document should be explicit enough for somebody on the outside to understand exactly how we make money.

See outline here
https://docs.google.com/document/d/1LXotim-sZgz1iM28ls95wX_B0HKu7oTs95YbXulu1tQ

**Definition of done:**

- [ ] Full draft of the commercial strategy created in the G Doc

**Not part of this task:**

1. review of the full draft
2. final version

**Comment by Mrak1985** [comment]
Lead of this project is Chris and Jack as a consultant

**Comment by Mrak1985** [comment]
https://docs.google.com/spreadsheets/d/1fSqw0IlirzbI0fdINnJlfT4GGHFcBKSXnM3KgdVrC3s/edit#gid=0

**Comment by Mrak1985** [comment]
13 Jack, 8 Misha
