### ISSUE TITLE
Meeting about usage how to use Tonomy ID - exact flow before marketing workshop

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#440]
**Description:**

- What is the purpose/reason for this task?
Have a big meeting with Jack and Chris at least 2 hours to align with basic view and usage Tonomy ID - what is Inside, what are the benefits for common people, will everyone just download it and use scanning their passport by NFC, how many countries uses chips for passports, driving license, really think the way 100% to be sure unique client meaning this the only one person in the world with that identity (how to tackle that?)
- What current or future goal of the TF does it help achieve?
To create marketing strategy for this

**Definition of done:**

- [x] meeting is held by all interested parties
- [x] meeting notes are written down

**Comment by nadiauqaili** [comment]
Hi! When will this meeting take place?

**Comment by Mrak1985** [comment]
@nadiauqaili  we have to setup may be next time

**Comment by Mrak1985** [comment]
https://docs.google.com/presentation/d/1-Foh4HhCdws0luBwjqHFys1ISPlHKxD33El4fJFTnrc/edit#slide=id.g1cb085594d8_0_21
