### ISSUE TITLE
Social media Tweeter managing

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#445]
**Description:**
Posting, commenting on Tweeter

- What is the purpose/reason for this task?
To have our presence on the platform
- What current or future goal of the TF does it help achieve?
To find potential customers

**Definition of done:**

- [x] necessary posts are made based on the relationship with other social media
- [x] Necessary content such as pictures, animations, videos are made

**Comment by Mrak1985** [comment]
@nadiauqaili @nvds888 fellows, you can choose who is gonna be. I will share password with Niels as well

**Comment by nadiauqaili** [comment]
We can both do it whenever we see fit according to our schedules. @nvds888 is that okay with you? Let me know!

**Comment by nvds888** [comment]
yes that is fine by me! We could do the platform's together to start off and focus on creating a working system for content scheduling
