### ISSUE TITLE
Setup meeting with Mariek de Ruyter

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#45]
**Description**

Marieke and the TNF have explored what they could do together and have more some kind of followup agreement (or not). 
Create outline of what you wish to acomplish 
Setup the meeting 
Have the meeting, make notes 
Set followup meeting 
Update CRM 
Check if you met objectives, report to the rocketchat 
set link here in Taiga to Notes 
Set task todone

**Definition of done:**

- [x] Meeting scheduled with Chris and Jack nad Mariek

**Comment by kamitor** [comment]
it is setup on MONDAY the 8th at 09:00
