### ISSUE TITLE
Website Contact page implementation

### ISSUE THREAD

**Issue by aymenae** [Tonomy-Foundation/management#456]
**Description:** We don't know what elements we want to put into the page exactly. We should research this so we do, ex. members/founder of Tonomy, a short description of what Tonomy is, how Tonomy started etc etc.

**Definition of done:**

- [x] Look at the template's pages, and decide what you're gonna use for it.
- [x] Look at the similar website for content inspiration (eg. length, type of content)
https://docs.google.com/document/d/18cowir-lgB8mdE0SwlZMheF64m5dCU9h/edit
- [x] Implement what you think fits on the page
- [ ] ask for feedback and improve your implementation as you go

**Comment by Xdsylar** [comment]
[https://app.zenhub.com/files/510762397/58e95a19-50c8-4db8-84c4-c895bab63fe6/download](https://app.zenhub.com/files/510762397/58e95a19-50c8-4db8-84c4-c895bab63fe6/download)

in this file is the code for the contact form which needs to be on the page
