### ISSUE TITLE
Follow up with Ruud van Fred from Windesheim to review tasks for Tonomy Lab 

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#469]
**Description:**
Follow up with Ruud van Fred from Windesheim to review tasks for Tonomy Lab 

- What is the purpose/reason for this task?
- What current or future goal of the TF does it help achieve?

**Definition of done:**

- [x] necessary communication is made

**Comment by kamitor** [comment]
[https://app.zenhub.com/files/510762397/7e19ea08-5b0f-464e-9b90-7e769c9a9f55/download](https://app.zenhub.com/files/510762397/7e19ea08-5b0f-464e-9b90-7e769c9a9f55/download)

**Comment by kamitor** [comment]
[https://app.zenhub.com/files/510762397/7e19ea08-5b0f-464e-9b90-7e769c9a9f55/download](https://app.zenhub.com/files/510762397/7e19ea08-5b0f-464e-9b90-7e769c9a9f55/download)

**Comment by kamitor** [comment]
[https://app.zenhub.com/files/510762397/7e19ea08-5b0f-464e-9b90-7e769c9a9f55/download](https://app.zenhub.com/files/510762397/7e19ea08-5b0f-464e-9b90-7e769c9a9f55/download)

**Comment by kamitor** [comment]
[https://app.zenhub.com/files/510762397/7e19ea08-5b0f-464e-9b90-7e769c9a9f55/download](https://app.zenhub.com/files/510762397/7e19ea08-5b0f-464e-9b90-7e769c9a9f55/download)

**Comment by kamitor** [comment]
[https://app.zenhub.com/files/510762397/7e19ea08-5b0f-464e-9b90-7e769c9a9f55/download](https://app.zenhub.com/files/510762397/7e19ea08-5b0f-464e-9b90-7e769c9a9f55/download)

**Comment by kamitor** [comment]
[https://app.zenhub.com/files/510762397/7e19ea08-5b0f-464e-9b90-7e769c9a9f55/download](https://app.zenhub.com/files/510762397/7e19ea08-5b0f-464e-9b90-7e769c9a9f55/download)

**Comment by kamitor** [comment]
[https://app.zenhub.com/files/510762397/7e19ea08-5b0f-464e-9b90-7e769c9a9f55/download](https://app.zenhub.com/files/510762397/7e19ea08-5b0f-464e-9b90-7e769c9a9f55/download)
