### ISSUE TITLE
Research and outline for opentech.fund

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#472]
https://apply.opentech.fund/internet-freedom-fund-concept-note/

Definition of done:

- [x]  Research Opentechfund for grant strategies
- [x]  Create the proposal outline that we could send to them
- [x]  Get feedback on the proposal outlines

**Comment by YegorTDK** [comment]
https://docs.google.com/document/d/1mHIRG94PqnBAhU3q9e6MjcGdZgu0u6vGN6s1dyaofcE/edit
