### ISSUE TITLE
Full draft proposal for opentech.fund

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#473]
https://apply.opentech.fund/internet-freedom-fund-concept-note/

Definition of done:

- [x]  Create a full draft of the proposal
- [x] get a review by Jack or Mike or Yegor

**Comment by YegorTDK** [comment]
https://www.opentech.fund/funds/

**Comment by YegorTDK** [comment]
https://docs.google.com/document/d/1mHIRG94PqnBAhU3q9e6MjcGdZgu0u6vGN6s1dyaofcE/edit

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/1FYh_TXgEUpHbV0epC1DRHCJD_KLG8WCaRKNMBoYt9lQ/edit
