### ISSUE TITLE
Website Tonomy ID page research

### ISSUE THREAD

**Issue by aymenae** [Tonomy-Foundation/management#480]
**Description:** we don't know what we want on the TID product page. Research competitors to find this out eg. content.

https://proofofhumanity.id/
https://jolocom.io/ and https://jolocom.io/blog/production-ready-smartwallet/
https://greymass.com/en/anchor/
https://trinsic.id/
https://www.brightid.org/
https://trustgrid.com/digital-citizen-identity/

**Definition of done:**

- [x] Went through the competitors' product pages
- [x] Made suggestions for the TID product page
- [x] Final product is knowing which elements are needed for the TID product page

**Comment by NotTheRealMax** [comment]
https://docs.google.com/document/d/1S-lMLZGHhtt3maQXEE51CJpejGkIyyyFOTUQ1zcBD_A/edit#
