### ISSUE TITLE
website TID product page content

### ISSUE THREAD

**Issue by aymenae** [Tonomy-Foundation/management#481]
**Description:** Go through this list & derive content for the TID page from it.
Value propositions here https://www.notion.so/tonomy-foundation/Onboarding-part-2-c1e2cda0bf8545b4897b3961576e6c7b#9ea96bb044574689833f3f178598efe6
Business model canvas' https://www.notion.so/tonomy-foundation/Business-Model-Canvas-Lean-Canvas-152ded7d5f9e44f384f7f68d9f84e8d7
Comparison https://docs.google.com/spreadsheets/d/11LOwU5AsAO6x0my9dPYrXGaT9norSuYfS-jWYOlgk1o/edit#gid=116682521
our white paper: https://github.com/Tonomy-Foundation/EOS-network-foundation-grant-framework/blob/tonomy-id/applications/tonomy-cross-platform-wallet.md
SSO demo https://tonomy-id-demo-market.vercel.app/ with play store app https://play.google.com/store/apps/details?id=foundation.tonomy.projects.tonomyidstaging
Presentaion: https://www.beautiful.ai/player/-N6SgveSn549hr03sE0z (you could also take images from here)

**Definition of done:**

- [x] Went through every content source
- [ ] Made content pieces for the TID product page from it (text only, with layout ideas if applicable)

**Comment by theblockstalk** [comment]
this was for the homepage https://docs.google.com/document/d/1QmT3B8kYUK6put4wZ1H5nPgBji9U7KkF8LBe2Sz5cwA/edit

**Comment by Riae** [comment]
Busy making content for the TID page docu using these.
