### ISSUE TITLE
Tonomy website latency homepage

### ISSUE THREAD

**Issue by aymenae** [Tonomy-Foundation/management#485]
**Description:** The latency on opening the page can be quite long, which is not good. This needs to be fixed.

**Definition of done:**

- [x] Measure latency on opening the page
- [x] Research fixes to lower latency
- [x] apply fixes to lower latency
- [x] measure new latency compared to old latency
- [x] get a review from Jack

**Comment by theblockstalk** [comment]
check the load of the whole page, and also see what assets take longer to load in the network tab
![image.png](https://images.zenhubusercontent.com/5ea82b5959354f2b8ef14f5d/f1fa689d-dce3-4378-bc8e-3bed5d54f774)

**Comment by TheFakeBasS** [comment]
Unable to find the svg files to convert to webp

**Comment by TheFakeBasS** [comment]
i have done what i can but it is taking too long to finish so i will drop the task
