### ISSUE TITLE
Tonomy website latency TID page

### ISSUE THREAD

**Issue by aymenae** [Tonomy-Foundation/management#486]
**Description:** The latency on opening the page can be quite long, which is not good. This needs to be fixed.

**Definition of done:**

- [ ] Measure latency on opening the page
- [ ] Research fixes to lower latency
- [ ] apply fixes to lower latency
- [ ] measure new latency compared to old latency
- [ ] get a review from Jack

**Comment by theblockstalk** [comment]
check the load of the whole page, and also see what assets take longer to load in the network tab
![image.png](https://images.zenhubusercontent.com/5ea82b5959354f2b8ef14f5d/f1fa689d-dce3-4378-bc8e-3bed5d54f774)
