### ISSUE TITLE
Research and outline for https://www.usaid.gov/div,

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#491]
https://www.usaid.gov/div,

Definition of done:

- [x]  Research https://www.usaid.gov/div, for grant strategies
- [x]  Create the proposal outline that we could send to them
- [x]  Get feedback on the proposal outlines

**Comment by YegorTDK** [comment]
https://docs.google.com/document/d/1vKM0eGOAxld53aOmh19siPPTwREkPKpzs7N1KDZrIog/edit - research
[https://app.zenhub.com/files/510762397/fa0f011f-114b-4be1-ae65-ae5799ba477b/download] - [https://app.zenhub.com/files/510762397/8d625960-b421-4fbe-90be-7e3fa396b2b1/download]
(https://app.zenhub.com/files/510762397/8d625960-b421-4fbe-90be-7e3fa396b2b1/download)

attached are a program statement with all the info and an application form

**Comment by Mrak1985** [comment]
I think it is a great opportunity @YegorTDK
