### ISSUE TITLE
Website TonomyID section 9; Get involved!

### ISSUE THREAD

**Issue by TheFakeBasS** [Tonomy-Foundation/management#499]
Create the "Get involved" component for the TonomyID page.
See the Page plans here;
https://docs.google.com/document/d/1S-lMLZGHhtt3maQXEE51CJpejGkIyyyFOTUQ1zcBD_A/

**definition of done**
- [x] View the section in the page plans
- [x] Go through the template and choose one fitting to the section
- [x] Implement the section as the page plan dictates
- [x] Add the page plan content to the component
- [x] Submit your product for feedback
- [ ] Reviewed & feedback implemented to satisfaction of PO

**Comment by Xdsylar** [comment]
![image.png](https://images.zenhubusercontent.com/63232ebaf7858659f273f64d/eb869f90-a090-402b-9fe0-d167f50929e5)

this is how it looks currently
