### ISSUE TITLE
EOS network foundation - update proposal

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#5]
Definition of Done:  

- [x] The proposal is clearly defined in a document, incuding all the links to those documents (the original proposal, where to find it and the output) ready for review here in the TAIGA.
- [x] Reach out to ONE person Review by either Chris / mike  / jack > Set the task to review
- [x]  Send out as draft to ENF community

This does NOT include   

1. Filing the proposal, Reviewing the proposal

**Comment by theblockstalk** [comment]
Proposal drafting
https://docs.google.com/document/d/1SkH27aCLzFVW6HkefONueJGMKOpsHMYgetPgWGYCqhw

**Comment by theblockstalk** [comment]
The proposal draft is finished and ready for review.

**Comment by theblockstalk** [comment]
@Mrak1985 Has done a review. I have sent this to the ENF and requested a meeting about it.

**Comment by theblockstalk** [comment]
Yves
```
I'm not sure what you mean by "matches what the ENF is looking for"?

The grant committee is comprised of 8 individuals, each with their own voice. Until it's formally submitted, there isn't much to discuss.

Once submitted, the operations team reviews to ensure the format was respected and the information was provided accordingly. After potential back and forth to get the application respecting the standard, it's sent to translation in preparation for submission to the committee.
```

**Comment by Mrak1985** [comment]
@theblockstalk if you finished, would you mind move it to done section please?
