### ISSUE TITLE
Explore grant proposals with ChefChain

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#50]
**Definition of done:**

- [x] One or more grant proposals are identified which could be co-proposed
- [x] agreement on whether we will co-propos

**Comment by kamitor** [comment]
Setting up proposal.

Need a couple of grants picked out already. looking at current grants we have

**Comment by kamitor** [comment]
Setting up proposal.

Need a couple of grants picked out already. looking at current grants we have

**Comment by kamitor** [comment]
Meeting tomorrow 12:th of june afternoon

**Comment by kamitor** [comment]
Meeting tomorrow 12:th of june afternoon

**Comment by kamitor** [comment]
https://www.romutrechtregion.nl/innoveren/

**Comment by kamitor** [comment]
https://business.gov.nl/subsidy/eurostars-subsidy-scheme/

**Comment by kamitor** [comment]
Call with https://innovation-funding.nl/ tomorrow 15:30
