### ISSUE TITLE
Based on the Feedback implement what it is needed

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#502]
Based on the task 482 implement correction for the entire page and sections

Def of done

- [ ] all is implemented from here https://docs.google.com/spreadsheets/d/19qUyRjeWYNiyWnsUPIlW_PP-1Lp3hwmi0BBBCuZTx70/edit#gid=0

**Comment by aymenae** [comment]
Added readme.md & went through reviews

**Comment by aymenae** [comment]
Added google analytics script to the website
