### ISSUE TITLE
Full draft proposal for https://www.usaid.gov/div,

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#505]
https://www.usaid.gov/div

https://docs.google.com/document/d/1vKM0eGOAxld53aOmh19siPPTwREkPKpzs7N1KDZrIog/edit - research

Definition of done:

- [ ]  Create a full draft of the proposal
- [ ]  get a review by Jack or Mike or Yegor

**Comment by YegorTDK** [comment]
https://docs.google.com/document/d/1lNG4Preo3Yc9l-DxHq8ZvszU9KPeIu7KrexRy7uHxh4/edit
