### ISSUE TITLE
 we shall split essential folders from nonessential 

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#508]
**Description:**
 we shall split essential folders from Marketing, for instance. Let’s create management folder and Share Tonomy

- What is the purpose/reason for this task?
To have better security
- What current or future goal of the TF does it help achieve?

**Definition of done:**

- [x] folders are split
- [x] people in charge are given access

**Comment by theblockstalk** [comment]
![image.png](https://images.zenhubusercontent.com/5ea82b5959354f2b8ef14f5d/5537035b-60ad-4c40-a5f7-95c074afe06c)

Done. Split into two and given everyone access to Operations.

Management and administration:
- Jack, Rebal, Chris, Mike have access
- Yegor has access to Grants
- Robert has access to Legal and Taxes

- CVs folder and Contributor sheet Have been moved to Operations, as they are necessary for onboarding process
