### ISSUE TITLE
Create an employee draft contract for sales or else positions

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#511]
As a nonprofit organization, create an employee draft contract for sales or other positions to clearly outline job responsibilities, expectations, and compensation for new hires.

Acceptance Criteria:

1. The contract includes the job title, job description, and responsibilities for the sales or other position.
2. The contract includes details on compensation, including salary, benefits, and commission structure (if applicable).
3. The contract includes details on the work schedule and hours, including any flexible or remote work arrangements.
4. The contract includes information on performance evaluation and feedback processes.
5. The contract includes details on the length of employment, any probationary periods, and termination procedures.

Definition of Done:

- [ ] The draft contract has been reviewed and approved by HR and legal departments.
- [ ] A finalized version of the contract has been shared with new hires and signed by both parties.
- [ ] A copy of the signed contract has been stored securely in the HR file for each employee.

**Comment by Robbort97** [comment]
Created a draft version of a temporary employment contract here: https://docs.google.com/document/d/1YZ-PF6ll2EjuDSK4mFcqNe3uSW-niq-Jl3N7XNC3AF8/edit# 

Dont know how to do the point about performance evaluation and feedback processes though
