### ISSUE TITLE
Figure out visa sponsorship for Diksha

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#513]
Description

It is the responsibility of the company to obtain the necessary sponsorship for the visa. You may want to research the process for obtaining a visa sponsorship for an employee in the Netherlands. This will likely involve filling out various forms and providing documentation to the relevant authorities. It is possible that you may need to engage the services of an immigration lawyer or other legal professional to assist with the process. Keep in mind that the requirements and procedures for obtaining a visa sponsorship can vary depending on the specific circumstances of the employee and the company, so it is important to carefully research the process and ensure that all necessary steps are taken in order to obtain the sponsorship.

As a non-profit foundation, it may be more difficult to obtain a visa sponsorship for an employee, as you do not have any employees at this time. However, this does not necessarily mean that it is impossible to bring Diksha to the Netherlands to work with your foundation. Some options that you could consider include:

Hiring Diksha as a consultant or contractor rather than an employee. This may make it easier to obtain the necessary visa sponsorship, as Diksha will not be considered an employee of the foundation.
Partnering with another organization that is able to sponsor Diksha's visa. This could involve entering into a joint project or collaboration with the other organization, with the understanding that they will provide the necessary sponsorship for Diksha's visa.
Applying for a grant or funding from a external organization or government agency that would allow you to bring Diksha to the Netherlands for a specific project or purpose. This funding could be used to cover the costs of obtaining the necessary visa sponsorship.
Ultimately, the best option will depend on the specific circumstances of your foundation and Diksha's situation. It may be helpful to speak with an immigration lawyer or other legal professional to get a better understanding of your options and the process for obtaining a visa sponsorship in the Netherlands.

Def of done:

- [x] research is done and solution either found or not
- [ ] it is documented in the kind of presentation or document

**Comment by Robbort97** [comment]
https://docs.google.com/presentation/d/1opCZxPD2UIBQ6box428Bmwm0T_L1o6AhVipiO5DmY6I/edit#slide=id.g1cd0b32d30b_0_18

**Comment by Robbort97** [comment]
https://docs.google.com/presentation/d/1Gh7vrmMBHm0_ribc5KM7MipRkFcicuFteY_zNuy28Jo/edit#slide=id.p

**Comment by Robbort97** [comment]
I've made 2 presentations. 1 that summarizes how Tonomy can become a sponsor and 1 for other ways that Diksha can get a residence permit
