### ISSUE TITLE
Apply for DigitalOcean Hatch program

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#523]
https://www.digitalocean.com/hatch

Description: DigitalOcean Hatch is an accelerator program for startups that provides funding, mentorship, and resources to help startups scale their businesses. To apply for this program, we will need to complete an application form, provide a pitch deck, and participate in a video interview.

Definition of Done: A completed application form, a pitch deck that highlights the value of our digital identity application, and a successful video interview with the DigitalOcean Hatch team.

How to reach the Definition of Done:

- [x] Research the DigitalOcean Hatch program and its requirements
- [ ] Prepare a pitch deck that highlights the value of our digital identity application, its impact on society and its cost-effectiveness.
- [ ] Complete the application form and submit it
- [ ] Prepare for the video interview by researching common questions and practicing answering them.
- [ ] Participate in the video interview and answer all the questions in a clear and concise manner.
- [ ] Follow up with the DigitalOcean Hatch team to ensure our application has been received and is being considered.

**Comment by theblockstalk** [comment]
done
