### ISSUE TITLE
Check if there are any legal/trademark issues with the name Tonomy

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#55]
**Definition of done:**

- [x] List created with companies and foundations with the same name and what activities they carry out

**Comment by Mrak1985** [comment]
Has started, doc is here https://docs.google.com/document/d/1jyA4WcZCY34N4MkNQHGMRXhvQiU7D8Hg2mcPHDDYeXU/edit

**Comment by Mrak1985** [comment]
@Carrie22022 @theblockstalk can one of you to review please?

**Comment by theblockstalk** [comment]
I have done some previous work in a project reviewing this kind of thing, with a lawyer to confirm. That said I am not a lawyer of course...

In my opinion, there are no medium to significant risks with any of the items in this list. Tonomy ( the only exact name clash) is in a sufficiently different field to us. The other ones do not have a significant risk due to not having a equally pronounceable name.
