### ISSUE TITLE
Apply for AWS Nonprofit Program

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#572]
As a member of Tonomy's technical team, I want to apply for the AWS Nonprofit Program so that Tonomy can take advantage of the discounts and benefits offered to eligible nonprofits.

https://aws.amazon.com/government-education/nonprofits/?nc1=h_ls&wwps-cards.sort-by=item.additionalFields.sortDate&wwps-cards.sort-order=desc

Definition of Done:

- [x] Review and understand the eligibility criteria for the AWS Nonprofit Program.
- [ ] Complete the application form on the AWS Nonprofit Program page.
- [ ] Provide all necessary documentation and information required for the application.
- [ ] Submit the application to AWS and follow up on the status.
- [ ] Document the process and any important information in Tonomy's records.

**Comment by theblockstalk** [comment]
@Mrak1985 if we have Digital Ocean credit then I'm not so keen to get AWS as well, as we want just one platform. Unless there is a MAJOR amount extra credit.

**Comment by Mrak1985** [comment]
No need to apply as it cost money from techsoup hopefully we will get digital ocean
