### ISSUE TITLE
Enhance Team Member's Salesforce Knowledge

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#573]
As a Tonomy Foundation team member, I want to receive training on how to use Salesforce efficiently and effectively, so that I can better perform my role within the organization.

Acceptance Criteria:

1. The necessary team members have been identified and selected to participate in the training.
2. A comprehensive training program has been chosen, which covers all the aspects of Salesforce that each team member needs to know. https://www.udemy.com/course/introduction-salesforce-non-profit-npsp/
3. The training is delivered during the sprint period, and team members have the opportunity to practice and apply what they have learned.
4. At the end of the training, team members will be able to demonstrate their understanding and ability to use Salesforce effectively.

Definition of Done:

- [ ] All necessary team members have completed the training program.
- [ ] Team members have been able to demonstrate their knowledge and understanding of Salesforce through practical exercises and assessments.
- [ ] Team members are able to apply their newfound knowledge in their day-to-day work, leading to improved productivity and efficiency.
- [ ] The impact of the training program has been evaluated, and any necessary improvements have been made for future training sessions.
- [ ] Check process of learning

**Comment by Mrak1985** [comment]
Per person

**Comment by Caihao013** [comment]
Done.

**Comment by kamitor** [comment]
salesforce flows for beginners

**Comment by kamitor** [comment]
https://m.youtube.com/watch?v=7_jaKoXmOK4

**Comment by kamitor** [comment]
@mike We need to watch this movie above and setup a saas flow with a dummy client where they automatically get billed in order to complete this task in my opinion

**Comment by Mrak1985** [comment]
Spandana 8

**Comment by kamitor** [comment]
We need to have an example Sales-Pipeline up and running that connects to all our systems, or this will be useless.

**Comment by theblockstalk** [comment]
closed as we are no longer using salesforce
