### ISSUE TITLE
to check and register https://nonprofithub.org/courses/

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#575]
As a manager at Tonomy, I want to explore and register on Nonprofithub's course platform so that Tonomy's team members can have access to educational resources and the opportunity to earn certificates for skill development in the future.

Definition of Done:

- [x] The manager has successfully navigated to https://nonprofithub.org/courses/
- [x] The manager has created an account on Nonprofithub

**Comment by kamitor** [comment]
what does this story build to?

**Comment by Mrak1985** [comment]
This portal has some free material, no need to register

**Comment by Mrak1985** [comment]
https://nonprofithub.org/free-guides-nonprofits/#finance

**Comment by Mrak1985** [comment]
https://drive.google.com/drive/u/0/folders/11sTkW20a40Mn7_3hTZjKukRc8PNnvnuQ
