### ISSUE TITLE
Fulldraft Secure - IT grant

### ISSUE THREAD

**Issue by kamitor** [Tonomy-Foundation/management#587]
As a grant writer, I want to create a full draft of the proposal for Secure - IT so that I can submit it to the grant review panel and have the best chance of receiving funding.
https://securit2.fundingbox.com/

Definition of Done:

- [x]  The proposal includes all the required information, such as background information on the project, project goals and objectives, project timeline and budget, and a detailed description of the activities that will be undertaken.
- [x]  The proposal is well-organized and easy to read, with clear and concise language.
- [x]  The proposal has been reviewed by either Jack, Mike, or Yegor and any necessary revisions have been made.
- [x]  The proposal is ready for submission to the grant review panel.

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/1FdEo7aVYFUayfP3QM_jehaPwAyaMjZ29FxxDCq3JO3o/edit

**Comment by Mrak1985** [comment]
Yegor, Tomas, and Jack have reviewed the Grant @kamitor please submit it. Each I suggest gets  8 points and 21 to you
