### ISSUE TITLE
Update onboarding

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#59]
**Definition of done:**
- [x] collect reviews from newcomers
- [x] adapt the onboarding workflow
- [x] have current employees go through the onboarding
- [x] implement feedback

**Comment by Mrak1985** [comment]
Yavuz review -
Some check boxed do not work - fixed
Put checklists on the left side - fixed
Describe more about Scrum - to be fixed
Texts are so long - to be fixed

**Comment by Mrak1985** [comment]
Milica - doctoral paper (give page numbers for what is necessary)
Give warm welcome to the new teammember
