### ISSUE TITLE
 Full draft proposal for https://nlnet.nl/core/

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#593]
As a grant writer, I want to create a full draft of the proposal for https://nlnet.nl/core/ so that I can submit it to the grant review panel and have the best chance of receiving funding.

Definition of Done:

- [x] The proposal includes all the required information, such as background information on the project, project goals and objectives, project timeline and budget, and a detailed description of the activities that will be undertaken.
- [x] The proposal is well-organized and easy to read, with clear and concise language.
- [x] The proposal has been reviewed by either Jack, Mike, or Yegor and any necessary revisions have been made.
- [x] The proposal is ready for submission to the grant review panel.

**Comment by YegorTDK** [comment]
link for the draft
https://docs.google.com/document/d/1q5HlNIzVLCoGLzH-IAZQUNX-lFy-sjOZnCuha4Lfocs/edit
