### ISSUE TITLE
Website full draft page for Tonomy ID

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#6]
Done

- [ ] Create full draft of Tonomy ID page on website with possibly new design

Not included

1. Review and final version published

**Comment by Mrak1985** [comment]
Chris wants to redo template

**Comment by kamitor** [comment]
>> move to tonomy - ID

**Comment by theblockstalk** [comment]
also here
https://github.com/Tonomy-Foundation/Tonomy-ID-Management/issues/10
