### ISSUE TITLE
Grant Research for a Non-Profit Organization

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#611]
Description:
As a member of a non-profit organization, you have been assigned the task of conducting grant research to identify potential funding sources. The goal of the research is to find grant opportunities that align with the organization's mission and programs. The research will involve reviewing various grant databases and websites, as well as contacting grantmakers to gather additional information.

Sub-tasks:

- [ ] Identify the organization's funding needs and goals for the upcoming year.
- [ ] Identify potential grant databases and websites to search for grant opportunities.
- [ ] Conduct a comprehensive search of the identified databases and websites for relevant grant opportunities.
- [ ] Identify grantmakers that are aligned with the organization's mission and programs.
- [ ] Contact grantmakers to gather additional information on their funding priorities and application requirements.
- [ ] Evaluate the identified grant opportunities and prioritize them based on their fit with the organization's needs and goals.
- [ ] Prepare a report summarizing the identified grant opportunities, including their deadlines, application requirements, and potential funding amounts.

**Comment by YegorTDK** [comment]
managed to find only 2 more opportunities, added to the list of grants
https://trustchain.ngi.eu/open-call-1/
https://www.ngi.eu/opencalls/#ngitrustchain
