### ISSUE TITLE
Check and Sign Contributor Contract Sadia

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#612]
https://docs.google.com/document/d/1lGwb5xXspH4JiehVebdZ2-4f2pe52n4mZKe2uJNHKco/edit

Task Description: As a part of the project's Scrum process, the contributor contract needs to be checked and signed by Sadia and Chris. The task involves the following steps:

- [x] Verify the current version of the contributor contract to ensure that it is up-to-date and in compliance with the project's legal requirements.
- [x] Notify Sadia and Chris that they need to sign the contributor contract.
- [x] Send the contributor contract to Sadia and Chris for review.
- [x] Follow up with Sadia and Chris to ensure that they have reviewed the contributor contract.
- [x] Collect the signed copies of the contributor contract from Sadia and Chris.
- [ ] Update the project records to reflect that Sadia and Chris have signed the contributor contract.
- [x] Communicate to the project team that the contributor contract has been signed and filed.

**Comment by kamitor** [comment]
I chris: hereby validate this contact.

**Comment by kamitor** [comment]
[Uploading... Contractor agreement Sadia.pdf]

**Comment by Mrak1985** [comment]
@kamitor please put it here https://drive.google.com/drive/u/0/folders/1lA1GM37c3DQmx8VQuvt1bUncv5bhwlSd and don't upload here personal info please

**Comment by Mrak1985** [comment]
@kamitor please put it here https://drive.google.com/drive/u/0/folders/1lA1GM37c3DQmx8VQuvt1bUncv5bhwlSd and don't upload here personal info please
