### ISSUE TITLE
 Scrum Master to Ensure Understanding of Scrum Framework and Zehhub Task Arrangement

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#614]
Task Description: As a part of the project's Scrum process, the Scrum Master needs to ensure that each team member understands how Scrum works and tasks in Zehhub are arranged. The task involves the following steps:

- [x] Schedule a meeting with each team member individually or as a group to review the Scrum framework and the project's use of Zehhub for task management.
- [x] Explain the key concepts of Scrum, including the roles of the Scrum Master, Product Owner, and Development Team, the Sprint cycle, and the Daily Scrum.
- [x] Discuss the team's use of Zehhub for task management, including how tasks are created, assigned, and tracked.
- [x] Review any issues or confusion the team members have had with Scrum or Zehhub and address them.
- [x] Ensure that each team member understands their role in the Scrum process and how they should interact with Zehhub.
- [x] Provide guidance and support to team members who may need additional assistance in understanding Scrum or Zehhub.
- [x] Encourage team members to ask questions and seek clarification on any areas of uncertainty.
- [x] Document the meeting and any feedback or issues raised during the meeting.

**Comment by BINLA123** [comment]
1. Meeting with Salah today to have a working agreement and synergy and also reaching out to connect with all my team members. DONE.
 2. Tomorrow will reach out to all my team members to get their availability so a meeting can be schedule for task614

**Comment by BINLA123** [comment]
Done meeting with Sarah and Yegor on Scrum Framework and Zenhub Board on the 03/03/2023

**Comment by BINLA123** [comment]
Meeting with PO on how to streamline the process and be more agile 06/03/2023

**Comment by BINLA123** [comment]
Had successful meeting with all my team members available and carried a feedback quality check and the results were amazing as we continue to learn and grow as a team, because the scrum frame and agile methodology as a whole is a continuous WIP
