### ISSUE TITLE
Apply for the NLnet Entrust Program

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#629]
As a researcher in the field of internet technology, I want to apply for the NLnet Entrust Program in order to obtain funding for my research project.

User Story:

As a researcher, I want to apply for the NLnet Entrust Program by submitting my project proposal and relevant documentation through their online application system. The system should allow me to easily upload my proposal and provide all the necessary information about my project and qualifications.

Definition of Done:

- [ ] The online application system allows the researcher to input all necessary information about their project and qualifications.
- [ ] The system allows the researcher to upload their project proposal and other relevant documentation.
- [ ] The system verifies that all required information has been provided before allowing the researcher to submit their application.
- [ ] The researcher receives a confirmation that their application has been successfully submitted.
- [ ] NLnet Entrust Program reviews the application and notifies the researcher about the status of their application.

**Comment by YegorTDK** [comment]
applied for the grant
link to the draft: https://docs.google.com/document/d/1pCbbE1FUANd69mTHTrYV7nHFDJLG5yQE0sxxfYfATXk/edit
