### ISSUE TITLE
Tonomy Management product backlog

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#63]
**Definition of done:**

- [x] Tonomy Management product backlog in Zenhub is organized, prioritized and with definition of done in all tasks by the start of sprint planning meeting

**Comment by theblockstalk** [comment]
Hey @Mrak1985 I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/tonomy-management-62c44570ca798a001824dd4d/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by kamitor** [comment]
For the future @Mrak1985 maybe more story points are needed for the proper planning of tasks in the future
