### ISSUE TITLE
Tonomy ID product backlog management

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#64]
**Definition of done:**

- [ ] Tonomy ID product backlog in Zenhub is organized, prioritized and with definition of done in all tasks by the start of sprint planning meeting

**Comment by theblockstalk** [comment]
Created to new epics and their associated tasks. I do not expect that we would finish these so I'm not creating more yet.

**Comment by kamitor** [comment]
@theblockstalk its simpler for me I just tell what is needed so not as much points needed!
