### ISSUE TITLE
Communicate with possible recruits

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#69]
**Description:**

https://tree.taiga.io/project/theblockstalk-tonomy-foundation/us/234?no-milestone=1

**Definition of done:**

- [x] Find different designers and ask how much it will cost their input for Tonomy ID
- [x] Ask 10 different developers to join the project

**Comment by Mrak1985** [comment]
Chris, if you feel to have completed this, please provide the evidence and move it to review row

**Comment by kamitor** [comment]
Mailed Mike the proof
