### ISSUE TITLE
Communicate with possible Partners

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#70]
**Description:**

We need to establish communication with a potential client. It can be anyone, just presenting our Foundation, sharing ideas, getting feedback

https://tree.taiga.io/project/theblockstalk-tonomy-foundation/us/235?no-milestone=1

**Definition of done:**

- [x] Communication was made and notes were taken

**Comment by theblockstalk** [comment]
Currently talking to
- Rewired One
- New Life
- Energy Web
- EOS Costa Rica

**Comment by theblockstalk** [comment]
also

- Sphereon

**Comment by theblockstalk** [comment]
All notes from meetings

- https://www.notion.so/tonomy-foundation/320602f5422949a2b814465a5e9354c2?v=6d5b01f1cf4f443cbd519a61c6a20fe6&p=5d9bfcb3009e4f54968b8b055f3ce8a3&pm=s
- https://www.notion.so/tonomy-foundation/320602f5422949a2b814465a5e9354c2?v=6d5b01f1cf4f443cbd519a61c6a20fe6&p=683dfed38d5e410a9b6e8be11c73ef10&pm=s
- https://www.notion.so/tonomy-foundation/320602f5422949a2b814465a5e9354c2?v=6d5b01f1cf4f443cbd519a61c6a20fe6&p=5b5aab60a4094e73af77a19fdfd00a42&pm=s
- https://www.notion.so/tonomy-foundation/320602f5422949a2b814465a5e9354c2?v=6d5b01f1cf4f443cbd519a61c6a20fe6&p=49482eabb14049a1a568748d6ff2e978&pm=s
- https://www.notion.so/tonomy-foundation/320602f5422949a2b814465a5e9354c2?v=6d5b01f1cf4f443cbd519a61c6a20fe6&p=ab41720182904bdd9253f288b320dcbc&pm=s
- https://www.notion.so/tonomy-foundation/320602f5422949a2b814465a5e9354c2?v=6d5b01f1cf4f443cbd519a61c6a20fe6&p=c4d9201ef63048468176e5206b46a7fc&pm=s

**Comment by Mrak1985** [comment]
Suggest to double points at least

**Comment by Mrak1985** [comment]
40 Points
