### ISSUE TITLE
Onboard new staff Robert and Aymen

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#72]
**Description:**
Onboarding new stuff using onboarding checklist in Notion

**Definition of done:**

- [x] Robert Onboarding
- [x] Aymen Onboarding
- [x] Administration Robert Zuidhof and agreement from school
 - [x] Meeting between Noortje & Chris (student councillor)

**Comment by kamitor** [comment]
Robert did the docs already
Just need to meet with the Councillor

**Comment by kamitor** [comment]
> Tasks IP & Voltuneer Agreement
> Rebal's contract check
> BV & Legal Stuff
