### ISSUE TITLE
Adjust onboarding based on Carrie's review

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#73]
**Description:**

Do you have a clear idea about what is expected of you at this job? 
Somewhat. I think the nature of the startup is sort of undefineable as we all work together to figure it out together. Haha. But I do know where to turn if I need clarification!

Is the job what you expected it to be? 
It is better. I truly appreciate working with everyone here!

Do you feel like you have all the tools and resources to perform your job successfully? 
Yes I do! If not, I can ask for them. I am not afraid to do so.

What can we do to help you do your job even better? 
Pay for the LinkedIn learning courses if possible! Maybe when we get funding.

What could we change or add to improve our onboarding process? 
List the folks names, skills, picture, (like a bio and how to reach them), also give everyone that works a lot an email and a calendar invitation application like Jack has.

What do you like the most about our onboarding process? 
Notion itself is a cool tool. I also like all the resources!

Is there something that you don’t like about our onboarding process? 
I think more information about the team will help connect us all together - maybe an introductory video or something. I think this is especially important as we are working remotely across the globe!

**Definition of done:**

- [x] Review Carrie's feedback
- [x] Make adjustment based on this review
- [x] Update the template if needed
- [ ] create process overview if needed

**Comment by theblockstalk** [comment]
todo
- [x] added team member info and how to contact
- [ ] info about two teams
- [x] add picture for all contributors
- [x] welcome video!?
- [x] streamline different topics for different contributors
- [ ] everyone have a tonomy email?

**Comment by theblockstalk** [comment]
feedback here
https://tonomyfoundation.rocket.chat/channel/general?msg=psvENKf4PHRMyKvCu
