### ISSUE TITLE
Volunteer agreement between Tonomy and any teammate

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#74]
**Description:**

herehttps://tree.taiga.io/project/theblockstalk-tonomy-foundation/us/345?no-milestone=1
**Definition of done:**

- [x] Agreement is created
- [x] Agreement is reviewed by other person
- [x] Review by legal guys
- [x] Link and agreement is in the Tonomy's folder
-

**Comment by kamitor** [comment]
Is een vrijwilligerscontract verplicht? Nee. In principe volstaat een mondeling vrijwilligerscontract en is een schriftelijke vrijwilligersovereenkomst niet verplicht.

Echter, wij raden je aan om wel een vrijwilligerscontract af te sluiten. Een vrijwilligerscontract is zowel in het belang van de organisatie, als van de vrijwilliger zelf.

A volunteer agreement is not a requirements in the netherlands. 

However it is recommended, 
Lets use the European Union's template and adapt it

file:///home/chris/Desktop/yia_2017_liite-vi_evs-volunteering-agreement_fi.pdf

I've made a document in https://docs.google.com/document/d/1nWJSxjDMHV-5ZOUOaIkcQ9aV-qKyZDnDO1uLTlKr6ck/edit?usp=sharing

**Comment by kamitor** [comment]
Made update on Deed of Transfer :)

**Comment by kamitor** [comment]
Shared with Rebal

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/1nWJSxjDMHV-5ZOUOaIkcQ9aV-qKyZDnDO1uLTlKr6ck/edit?usp=sharing   @kamitor we used to have link above for volunteer agreement and you created it btw))

**Comment by kamitor** [comment]
Now with Legal Person

**Comment by Mrak1985** [comment]
You can contact the UWV with questions about your employment contract. You can also use the free legal services of ‘Het Juridischloket’, or have a 10-minute free of charge consultation on employment issues at the Legal Expat Desk of the law firm ‘GMW Lawyers’.
Can you ask those guys in 10 mins free time consultation - if we ask people to give up IP rights, is it fine if they have no contract with us? If they sue us for not paying them and taking all their IP for free? If it is not ok, will volunteer agreemet solve this problem?
if yes, can we pay nothing based a on volunteer agreement?
also can we pay by tokens which generally cost nothing and people won't sue us for zero value?

**Comment by kamitor** [comment]
https://docs.google.com/document/d/1TYFOAmVtK__F5Q6nK-OAh0ko3qLwiuIC9MTBfXY9L3Q/edit#

**Comment by Mrak1985** [comment]
This is not an IP agreement, this is volunteer (contract) agreement

**Comment by kamitor** [comment]
Send to official legal for review

**Comment by kamitor** [comment]
https://drive.google.com/drive/folders/1UszppZvl7hG3Pe1HBaAM_ry7G6MUj090

**Comment by Robbort97** [comment]
Mike and I agreed that a volunteer agreement is not really relevant. 

If it's just to make sure they can't get their IP rights back or to determine their compensation then it's really not neccesary. Owners of an IP are free to transfer/assign as they wish. Payment is not necessary. I checked the tax authorities website and volunteer compensation is only taxed above a certain amount of euro's. So as long as we don't pay that and the tokens aren't worth that much there is no problem. And if there is a mutual understanding between Tonomy and it's members that payment is in tokens then that is fine too. Doesn't need to be in writing. If there is a dispute with a member about the payment, then everyone can vouch that they knew that payment was in tokens.

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/13OztCU6S9drnt9Wk2Z5qxJtxvOTbTm456XvjPYnJtFs/edit
