### ISSUE TITLE
Website homepage upgrades Prototype

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#8]
Done

Research

- [ ] The overall look.
- [ ] Information on the homepage.
- [ ] Responsiveness of the Homepage.
- [ ] Current features.

Upgrade
- [ ] The overall look.
- [ ] Information on the homepage.
- [ ] Responsiveness of the Homepage.
- [ ] Current features.

**Comment by kamitor** [comment]
Blocked on site giving errors.
Some Database errors.
