### ISSUE TITLE
Ford Foundation grant proposal outline

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#82]
**Definition of done:**

- [x] Review the proposal and research what they are looking for https://www.fordfoundation.org/work/our-grants/how-we-make-grants/
- [ ] Check that Tonomy Foundation meets legal, financial and other conditions for the proposal
- [ ] Brainstorm ideas for what we can propose
- [ ] Create a Google Docs with all of the questions that need to be answered to fill out the proposal
- [ ] Outline/summary of what we propose is created
- [ ] Review outline/summary and agreed on by 1 other person

**Comment by Mrak1985** [comment]
https://www.fordfoundation.org/work/our-grants/

**Comment by Mrak1985** [comment]
There is no grants at the moment, so I put that to blocked section - no current opportunity, check it after 2 weeks time

**Comment by YegorTDK** [comment]
[https://app.zenhub.com/files/510762397/d84f2030-ce98-40ce-a68d-4cb8e0f1be0a/download](https://app.zenhub.com/files/510762397/d84f2030-ce98-40ce-a68d-4cb8e0f1be0a/download)

FordFoundation application guide for future use
