### ISSUE TITLE
Grant: Soros Economic Development Fund

### ISSUE THREAD

**Issue by Carrie22022** [Tonomy-Foundation/management#83]
**Definition of done:**

- [ ] Review the proposal and research what they are looking for
- [ ] Check that Tonomy Foundation meets legal, financial and other conditions for the proposal
- [ ] Brainstorm ideas for what we can propose (suggested in a call after two people have done review of proposal)
- [ ] Create a Google Docs with all of the questions that need to be answered to fill out the proposal
- [ ] Outline/summary of what we propose is created
- [ ] Review outline/summary and agreed on by 1 other

**Comment by Mrak1985** [comment]
https://www.soroseconomicdevelopmentfund.org/who-we-are

**Comment by kamitor** [comment]
Check with Carrie First > 
Continue Doing it...
Needs to select one:
Other Tasks took priority > Ongoing tasks
Mistake to start the task and not finish it

**Comment by kamitor** [comment]
Check with Carrie First > 
Continue Doing it...
Needs to select one:
Other Tasks took priority > Ongoing tasks
Mistake to start the task and not finish it

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/1lbTTcQHqAxYo69SXeXqESS6f7-9R1A5eDcED7y2_me0/edit

**Comment by Carrie22022** [comment]
I reached out to the Soros team with the following: 

Hello, 

I am part of a startup that creates an economy of trust and gives sovereignty back to the individual through digital ownership and protection of all information and transactions. We'd love to become part of your mission and combine forces. How could we accomplish these wonderful things together? 

Carrie
