### ISSUE TITLE
Send IP to legal people and make all teammates to sign IP agreement

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#84]
**Description:**

https://docs.google.com/document/d/1tzOfMp_7CaPQbEpsUqsORRi57LQFtcmAlFrXOjpBROY/edit

**Definition of done:**

- [x] Give to legal people to review
- [x] Put to the legal folder as a template
- [x] Make all teammates to sign it

**Comment by kamitor** [comment]
There is no legal people unless you want me to hire them

**Comment by Mrak1985** [comment]
@kamitor I thought you were saying, that you have some legal people who can review it for free, didn't you?

**Comment by Mrak1985** [comment]
https://drive.google.com/drive/u/2/folders/1MR40lnc5gqtAHTgXXtDQBbexgWewKf2L

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/1TYFOAmVtK__F5Q6nK-OAh0ko3qLwiuIC9MTBfXY9L3Q/edit#

**Comment by Mrak1985** [comment]
has not met definition of done

**Comment by kamitor** [comment]
Going to delegate the final version to our new law intern

**Comment by Mrak1985** [comment]
Jack has signed, we need another task to sign for all teammates as we had created this one, we had less members

**Comment by Mrak1985** [comment]
@YegorTDK needs to have some points for review
