### ISSUE TITLE
Gender equality plan research and create

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#86]
**Description:**
Based on the links below, research and create GEP and put it in our folder. We need this document to have an opportunity to apply for different grants of Europa.eu
https://ec.europa.eu/info/funding-tenders/opportunities/docs/2021-2027/horizon/guidance/programme-guide_horizon_en.pdf
https://ec.europa.eu/info/research-and-innovation/strategy/strategy-2020-2024/democracy-and-rights/gender-equality-research-and-innovation_en#gender-equality-plans-as-an-eligibility-criterion-in-horizon-europe

**Definition of done:**

- [x] Research on how to create GEP
- [ ] Create and Sign GEP
- [ ] Put it in our google drive

**Comment by Mrak1985** [comment]
Watching video, a lot of material https://youtu.be/0gZyhhnStX4

Guidance supports organisations to meet the Gender Equality Plan (GEP) 
https://op.europa.eu/en/publication-detail/-/publication/ffcb06c3-200a-11ec-bd8e-01aa75ed71a1/language-en/format-PDF/source-232129669

**Comment by Mrak1985** [comment]
We do not have to create GEP as we are non-profit organisation but it will be nice to have though it will take a lot of time and effort which is now not essential. But we all must remember about equality, respect and mutual help
![Screenshot_2022-07-27-12-20-49-36_e2d5b3f32b79de1d45acd1fad96fbb0f.jpg](https://images.zenhubusercontent.com/62c6a6e69c59cc221bd21079/c4e759a2-c6dd-4f5d-8e00-a098da94c12d)

**Comment by kamitor** [comment]
We dont need a gender equality plan for a non-profit organisation. 
Would be nice to have it in the future, to be on the "correct' or safe side to be in line with future organisation. But at the moment we don't need it for the european union grant. 

It would involve the entire team: How each members feel about skin color and genders, eyes. 
Just for now we need to understand that : we need to respect eachothers feelings, genders and cultural background.

Closed for now, in the future it is needed its part of HR.
