### ISSUE TITLE
Go through the NLNet grant application providers and search for partneships of interest

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#87]
**Description:**

NLNet suggests several other places to look for funding. We should vo through this to find companies and foundations that are giving grants or supporting projects like ours.

This helps us find grant funding and potential publicity and reputational partners.

**Definition of done:**

- [x] Existing and past grants are checked for the organisations that are backing them. https://nlnet.nl/foundation/network.html
- [x] Relevant companies are added to the CRM or the Grants sheet
https://docs.google.com/spreadsheets/d/1ZScGmG5sNVsQGpcvYQq8_k55dFlfgvFWsLiZm5-tKsU/edit#gid=379964154
https://docs.google.com/spreadsheets/d/1bTlfYU6H9xQHdszdiw6kpV3FgYXPgkaAVR3kpYVdZSs/edit#gid=697017607
- [x] When relevant, and suggested as a new task in Rocket Chat

**Comment by Mrak1985** [comment]
@YegorTDK sorry, I can't find your comments about this research on Discord, if you can, can you please add that is the final decision here - for instance do we have right candidates to apply for, etc,
