### ISSUE TITLE
Consider open source replacement of Notion

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#88]
**Description:**

Notion is our wiki tool. It is closed source and costs a lot. This task would be to replace this with a usable, open source and cost-effective tool. This can help us be transparent and stay aligned with our open source goals.

**Definition of done:**

- [ ] Check out https://hedgedoc.org/
- [ ] Checkout https://alternativeto.net/software/codimd/
- [ ] Decide if we want to switch

**Comment by Mrak1985** [comment]
Duplicate of #2
