### ISSUE TITLE
NGI Call 10 and NGI Entrust proposal 2 full drafh

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#91]
**Definition of done:**

- [ ] Full draft of the proposal

**Comment by theblockstalk** [comment]
here it is
https://docs.google.com/document/d/1sb1dEeMZR9kdF3clJlbXgYYMYKzd-Qk5fENaGfYVtZk/edit#

**Comment by Mrak1985** [comment]
@theblockstalk Reviewed

**Comment by Mrak1985** [comment]
Jack, in 3 tasks on Zenhub I can't find this Decentralized Encryption Key Recovery link, in 2 tasks the same link with Sovereign VC Consent

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/1Zq0vPw5zhqblfmeeoWjYlV7tCbkzHsKrwgpfnpqycyA/edit#heading=h.q9nyd79i5ah2
