### ISSUE TITLE
Finalise and submit NGI Azure call 10 proposal

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#92]
**Definition of done:**

- [x] Get feedback based on full draft for each proposal
- [x] Proposals are finalised based on feedback
- [x] Proposals are submitted

**Comment by theblockstalk** [comment]
here is the draft

**Comment by Carrie22022** [comment]
Carrie reviewed 7/18/22 - left suggestions

**Comment by Mrak1985** [comment]
I've reviewed

**Comment by theblockstalk** [comment]
Proposal 1 - Verifiable Conditions, has been submitted to NGI Azure through NLNet. Submission code 2022-08-032
@Carrie22022

**Comment by kamitor** [comment]
I have added jack to this card as assigned.
