### ISSUE TITLE
Finalise and submit NGI Entrust proposal

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/management#93]
**Definition of done:**

- [x] Get feedback based on full draft each 3 of proposals
- [x] Proposals are finalised based on feedback
- [x] Proposals are submitted

**Comment by kamitor** [comment]
I have added Jack as the assigned person

**Comment by kamitor** [comment]
Actually, CARRIE did this :D

**Comment by kamitor** [comment]
Review was done by Jack 
Mike didnt had a chance to review, 

So where is the grant right now, (the text? )
