### ISSUE TITLE
Tonomy Management product backlog

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#95]
**Description:**

Springt from 19 Jul - 02 Aug 22

**Definition of done:**

- [ ] Tonomy Management product backlog in Zenhub is organized, prioritized and with definition of done in all tasks by the start of sprint planning meeting
- [ ] meeting with marketing
- [x] meeting with finance
- [ ] meeting with HR
- [ ] meeting with Development
- [ ] meeting with Projects

**Comment by kamitor** [comment]
Will be finished tomorrow >> Followup

**Comment by kamitor** [comment]
This is a daily routine

Catch up with the rest of the team : > and then add the things to the product backlog.
