### ISSUE TITLE
Create Deck\table with Contributor's token explanation

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#97]
**Description:**

It should be clear for everyone how much they will get a month with contributor tokens and to show how it can be affected by tax. What is DCF explanation as well

**Definition of done:**

- [x] Pitch deck is created
- [x] sent to everyone
- [x] get feedback from people who participated and sum up

**Comment by Mrak1985** [comment]
https://www.loom.com/share/160a4489c0c8428eadaa3db56ad32fab  - Pitch itself

https://docs.google.com/spreadsheets/d/1tXb8BeR1qGkjehDD8xOVDpapY8D17M09ndt-N4MpElY/edit#gid=0  - document to calculate

**Comment by theblockstalk** [comment]
hey @Mrak1985 just looked at this. i thought it was a bit heavy to talk through, and that you were going to make some charts? so i very quickly created another sheet to see what it would like like - makes it clearer to me. what do you think?
https://docs.google.com/spreadsheets/d/1tXb8BeR1qGkjehDD8xOVDpapY8D17M09ndt-N4MpElY/edit#gid=778622290

**Comment by kamitor** [comment]
needs feedback from everyone and a followup meet with a official agreement 
>> New Task for sprint

Carrie to be added as assignee
