### ISSUE TITLE
Create short and long term strategy for marketing

### ISSUE THREAD

**Issue by Mrak1985** [Tonomy-Foundation/management#99]
**Description:**

We have to create a document which will describe our long and short term strategy for marketing. It should be clear which audience we are targeting, how we dow it, how many resources we need and what is expected output we desire to get

**Definition of done:**

- [x] Document is created
- [x] Reviewed by interested people (at least one)
- [x] It is on Tonomy google drive folder marketing

**Comment by kamitor** [comment]
https://docs.google.com/presentation/d/1g1ZX7y6H3JtixmEdieMuzajHPosALIqzs89Qjj9rPwE/edit#slide=id.g135a06b664d_0_430

**Comment by kamitor** [comment]
But is not yet completed

**Comment by Mrak1985** [comment]
https://docs.google.com/document/d/1vNcpo6C9FnBSi2rk1UKkmiQiNSeE57w5s9gV2LFeUII/edit
